"""add_outbox_lease

Revision ID: 9da4966d071d
Revises: 5a7ca645df3b
Create Date: 2026-08-04 03:25:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9da4966d071d"
down_revision = "5a7ca645df3b"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("outbox", sa.Column("owner_token", sa.String(length=128), nullable=True))
    op.add_column(
        "outbox", sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("outbox", "lease_expires_at")
    op.drop_column("outbox", "owner_token")
    # ### end Alembic commands ###
