import structlog
from dependency_injector.wiring import Provide, inject
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession, async_sessionmaker

from notification.bootstrap.container import Container

logger = structlog.get_logger(__name__)
router = APIRouter(prefix="/api/v1/notifications", tags=["notifications"])

# Strict Event-Driven Architecture:
# We do not expose synchronous REST endpoints for dispatching notifications.
# The Notification engine runs as a consumer listening to the SQS queue,
# processing Domain Events generated by upstream services via their local outboxes.


@router.get("/health", status_code=status.HTTP_200_OK)
async def health_check() -> dict[str, str]:
    """Lightweight liveness check - always returns OK if the service is running."""
    return {"status": "OK", "service": "notification"}


@router.get("/ready", status_code=status.HTTP_200_OK)
@inject
async def readiness_check(
    session_factory: async_sessionmaker[AsyncSession] = Depends(Provide[Container.session_factory]),  # noqa: B008
) -> dict[str, str]:
    """
    Readiness check - verifies critical dependencies are available before serving traffic.
    Checks DB connectivity, Postgres listener, and SQS consumer health.
    """
    try:
        async with session_factory() as session:
            await session.execute(text("SELECT 1"))

        # TODO: Add checks for Postgres listener and SQS consumer health
        # These would require access to the listener and consumer instances
        # which may need to be registered in the container

        return {"status": "ready", "service": "notification"}
    except Exception:
        logger.exception("Readiness check failed")
        raise HTTPException(
            status_code=status.HTTP_503_SERVICE_UNAVAILABLE,
            detail="Service not ready",
        )
