from pathlib import Path


def build_registry():
    base_dir = Path(__file__).parent
    registry = {}

    # We will walk through 'x12' and 'edifact' folders.
    for standard in ['x12', 'edifact']:
        standard_dir = base_dir / standard
        if not standard_dir.exists():
            continue

        for path in standard_dir.rglob("*.py"):
            if path.name == '__init__.py':
                continue

            # Remove the base_dir to get relative parts
            rel_path = path.relative_to(base_dir)
            parts = rel_path.parts

            # Module path e.g. edi_grammar.x12.4010.850004010
            module_path = "edi_grammar." + ".".join(parts)[:-3] # strip .py

            # The lookup key should be standard.filename_without_extension
            # e.g., "x12.850004010"
            lookup_key = f"{standard}.{path.stem}"
            registry[lookup_key] = module_path

    out_file = base_dir / "registry.py"
    with open(out_file, "w") as f:
        f.write("# AUTO-GENERATED BY build_registry.py\n")
        f.write("GRAMMAR_REGISTRY = {\n")
        for key in sorted(registry.keys()):
            f.write(f'    "{key}": "{registry[key]}",\n')
        f.write("}\n")

    print(f"Registry built with {len(registry)} entries.")

if __name__ == '__main__':
    build_registry()
