import json
import os
import shutil
import subprocess
import sys

DOCKER_BIN = shutil.which("docker")
TERRAFORM_BIN = shutil.which("terraform")

if not DOCKER_BIN:
    raise RuntimeError("docker binary not found in PATH")
if not TERRAFORM_BIN:
    raise RuntimeError("terraform binary not found in PATH")

import structlog

logger = structlog.get_logger(__name__)
import time
from pathlib import Path


def wait_for_file(file_path: Path, max_wait_ms: int = 60000) -> None:
    """Block until file_path exists or max_wait_ms elapses."""
    start_time = time.time()
    logger.info("Waiting for file to be generated by Zitadel...", file_path=str(file_path))
    while (time.time() - start_time) * 1000 < max_wait_ms:
        if file_path.exists():
            logger.info("File found!")
            return
        time.sleep(1)
    raise TimeoutError("Timeout waiting for file")


def _count_provisioned_resources(tf_state_path: Path) -> int:
    """Return the number of resources in the Terraform state, or 0 if unreadable."""
    if not tf_state_path.exists():
        return 0
    try:
        state = json.loads(tf_state_path.read_text(encoding="utf-8"))
        return len(state.get("resources", []))
    except (json.JSONDecodeError, KeyError, OSError):
        return 0


def _destroy_existing(script_dir: Path, root_dir: Path) -> None:
    """
    Reset Zitadel to a completely clean state:
      1. Wipe Terraform state files — Terraform's record of what it built.
      2. Delete any leftover pat.json — it is a BIND MOUNT (not a Docker volume),
         so `docker compose down -v` does NOT remove it. A stale pat.json contains
         a PAT tied to the now-wiped database; using it would cause AUTH-7fs1e.
      3. Stop containers and delete volumes — destroys the Postgres database.

    We do NOT need `terraform destroy`. Deleting the database volume already removes
    every Zitadel resource at the storage level. The state file and pat.json are the
    only host-filesystem artefacts that must be cleared explicitly.
    """
    logger.info("🔥 Resetting existing Zitadel state...")

    # Step 1: Clear Terraform state so the next apply treats this as a first run
    for state_file in ["terraform.tfstate", "terraform.tfstate.backup"]:
        path = script_dir / state_file
        if path.exists():
            path.unlink()
            logger.info("Cleared state file", state_file=state_file)

    # Step 2: Delete stale pat.json from the bind-mount directory.
    # docker compose down -v does NOT delete bind-mounted host directories.
    pat_key_path = script_dir / "machinekey" / "pat.json"
    if pat_key_path.exists():
        pat_key_path.unlink()
        logger.info("  Cleared: machinekey/pat.json (stale token for wiped database)")

    # Step 3: Stop ALL containers and wipe all named volumes (destroys Postgres databases)
    # This ensures that when Zitadel is reset, all downstream apps are also wiped,
    # preventing stale ID references (e.g., idp_user_id conflicts).
    subprocess.run(  # noqa: S603 - Docker compose is a trusted local executable
        [
            DOCKER_BIN,
            "compose",
            "-f",
            "docker-compose.yml",
            "-f",
            "docker-compose.identity.yml",
            "down",
            "-v",
            "--remove-orphans",
        ],
        cwd=root_dir,
        check=True,
    )

    logger.info("✅ Full infrastructure state cleared. Ready for fresh bootstrap.")


def _sync_outputs_to_env(root_dir: Path) -> None:
    """
    Sync Terraform outputs to .env by calling sync.py directly
    (avoids a cross-runtime dependency on pnpm/Node.js).
    """
    sync_script = root_dir / "infra" / "cloud" / "zitadel" / "sync.py"
    subprocess.run([sys.executable, str(sync_script)], cwd=root_dir, check=True)  # noqa: S603 - sys.executable is a trusted path


def _run_full_bootstrap(script_dir: Path, root_dir: Path, pat_key_path: Path) -> None:
    """
    Full bootstrap flow:
      1. Start Zitadel (fresh database generates a new ephemeral PAT)
      2. Wait for the ephemeral PAT
      3. Provision Zitadel resources with Terraform
      4. Sync Terraform outputs to .env
      5. Delete the ephemeral PAT
    """
    # Start Zitadel so it generates a fresh PAT on the clean database
    subprocess.run(  # noqa: S603 - Docker compose is a trusted local executable
        [DOCKER_BIN, "compose", "-f", "docker-compose.identity.yml", "up", "-d"],
        cwd=root_dir,
        check=True,
    )

    # Wait for Zitadel's FirstInstance job to write the ephemeral PAT
    wait_for_file(pat_key_path)

    # Read the raw PAT (plain token or JSON-wrapped)
    raw_key = pat_key_path.read_text(encoding="utf-8").strip()
    actual_token = raw_key
    if raw_key.startswith("{"):
        try:
            key_data = json.loads(raw_key)
            actual_token = key_data.get("token") or key_data.get("Token") or raw_key
        except json.JSONDecodeError:
            pass  # raw_key is already the plain token string

    logger.info("Successfully read PAT from pat.json")

    # Wait for Zitadel's CQRS projections to settle before Terraform queries them
    logger.info("Waiting 15 seconds for Zitadel projections to settle...")
    time.sleep(15)

    try:
        # Provision Zitadel IAM resources via Terraform
        logger.info("Running terraform init...")
        subprocess.run([TERRAFORM_BIN, "init"], cwd=script_dir, check=True)  # noqa: S603 - Terraform is a trusted local executable

        logger.info("Applying Terraform configuration...")
        env = os.environ.copy()
        env["TF_VAR_zitadel_token"] = actual_token
        subprocess.run(  # noqa: S603 - Terraform is a trusted local executable
            [TERRAFORM_BIN, "apply", "-var-file=local.tfvars.example", "-auto-approve"],
            cwd=script_dir,
            env=env,
            check=True,
        )

        # Sync the new outputs to .env
        _sync_outputs_to_env(root_dir)

        logger.info("✅ Zitadel bootstrap completed successfully!")
    finally:
        # Cleanup the ephemeral PAT — it must not linger on disk
        logger.info("Cleaning up local ephemeral PAT file by deleting pat.json...")
        if pat_key_path.exists():
            pat_key_path.unlink()


def main() -> None:
    script_dir = Path(__file__).parent.resolve()
    root_dir = script_dir.parent.parent.parent
    pat_key_path = script_dir / "machinekey" / "pat.json"
    tf_state_path = script_dir / "terraform.tfstate"

    resource_count = _count_provisioned_resources(tf_state_path)

    if "--reset" in sys.argv and resource_count > 0:
        _destroy_existing(script_dir, root_dir)

    _run_full_bootstrap(script_dir, root_dir, pat_key_path)


if __name__ == "__main__":
    try:
        main()
    except TimeoutError:
        logger.exception("\n❌ Bootstrap timed out")
        sys.exit(1)
    except RuntimeError:
        logger.exception("\n❌ Bootstrap configuration error")
        sys.exit(1)
    except subprocess.CalledProcessError:
        sys.exit(1)
    except KeyboardInterrupt:
        logger.exception("\nBootstrap cancelled by user.")
        sys.exit(0)
