import { execSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '../../..');

const patKeyPath = path.join(__dirname, 'machinekey', 'pat.json');
const envPath = path.join(rootDir, '.env');

async function waitForFile(filePath: string, maxWaitMs = 60000): Promise<void> {
  const start = Date.now();
  console.log(`Waiting for ${filePath} to be generated by Zitadel...`);

  while (Date.now() - start < maxWaitMs) {
    if (fs.existsSync(filePath)) {
      console.log('File found!');
      return;
    }
    await new Promise((resolve) => setTimeout(resolve, 1000));
  }

  throw new Error(`Timeout waiting for ${filePath} after ${maxWaitMs}ms`);
}

async function main() {
  try {
    // 1. Wait for the key to be generated by Zitadel FirstInstance
    await waitForFile(patKeyPath);

    // 2. Read the PAT
    const rawKey = fs.readFileSync(patKeyPath, 'utf-8').trim();
    let actualToken = rawKey;

    // Fallback if it actually IS JSON somehow
    if (rawKey.startsWith('{')) {
      const keyData = JSON.parse(rawKey);
      actualToken = keyData.token || keyData.Token || keyData;
      if (keyData && typeof keyData === 'object' && keyData.token) actualToken = keyData.token;
    }

    console.log('Successfully read PAT from pat.json');

    // Wait for Zitadel CQRS projections to settle
    console.log('Waiting 15 seconds for Zitadel projections to settle...');
    await new Promise((resolve) => setTimeout(resolve, 15000));

    // 3. Run Terraform to setup Zitadel
    console.log('Resetting local terraform state and applying configuration...');
    execSync('rm -f terraform.tfstate*', { cwd: __dirname, stdio: 'inherit' });
    execSync('terraform init', { cwd: __dirname, stdio: 'inherit' });
    execSync('terraform apply -var-file=local.tfvars.example -auto-approve', {
      cwd: __dirname,
      stdio: 'inherit',
      env: { ...process.env, TF_VAR_zitadel_token: actualToken },
    });

    // 5. Sync Identity outputs to .env
    console.log('Syncing Terraform outputs back to .env...');
    execSync('pnpm infra:sync-identity', { cwd: rootDir, stdio: 'inherit' });

    console.log('✅ Zitadel automated bootstrap completed successfully!');
  } catch (err) {
    console.error('Error during bootstrap:', err);
    process.exit(1);
  }
}

main();
