encryptionsalt: v1:xDorJiTx8yw=:v1:WKYbdgfytKHfqLPL:3UdMPjc7L8k+2egxLEaqaFNECuSd7w==
config:
  zitadel-infrastructure:insecure: "true"
  zitadel-infrastructure:port: "8080"
  zitadel-infrastructure:platform_admin_password:
    secure: v1:kB3N22XNxvRZYnGm:nBjRZH0lFvFP2fB4YA8GT0tXCUPivgXjEhQ=
