encryptionsalt: v1:XP0KYO2Tf3w=:v1:jYi3QaSan9faRQhg:uYA7BnXex+/TLLzjD4ZdiuAerYyE2w==
config:
  zitadel-infrastructure:insecure: "true"
  zitadel-infrastructure:port: "8080"
  zitadel-infrastructure:platform_admin_password:
    secure: v1:zj0MxmrNbP59qUpl:KT39CAhVic/oBPuppXE1zEY9uS/g3Y53vIW1mmQLrkdR
