from enum import StrEnum


class UcpJobName(StrEnum):
    UCP_OUTBOX_SWEEPER = "UCP_OUTBOX_SWEEPER"
    UCP_OUTBOX_CLEANUP = "UCP_OUTBOX_CLEANUP"
    UCP_IDEMPOTENCY_CLEANUP = "UCP_IDEMPOTENCY_CLEANUP"
    UCP_AUDIT_LOG_CLEANUP = "UCP_AUDIT_LOG_CLEANUP"
