import * as crypto from 'crypto';

export class ApiKey {
  constructor(
    public readonly id: string,
    public readonly tenantId: string,
    public readonly name: string,
    public readonly keyHash: string,
    public readonly scopes: string[],
    public readonly createdAt: Date,
  ) {}

  static generate(
    tenantId: string,
    name: string,
    scopes: string[],
  ): { apiKey: ApiKey; rawSecret: string } {
    const rawSecret = crypto.randomBytes(32).toString('hex');
    const keyHash = crypto.createHash('sha256').update(rawSecret).digest('hex');

    // Typically ID would be generated by DB or CUID, but we can provide a prefix for clarity
    const id = `apk_${crypto.randomBytes(12).toString('hex')}`;

    const apiKey = new ApiKey(id, tenantId, name, keyHash, scopes, new Date());
    return { apiKey, rawSecret };
  }

  static hashSecret(rawSecret: string): string {
    return crypto.createHash('sha256').update(rawSecret).digest('hex');
  }
}
