export enum ConfigKey {
  SNS_TENANT_EVENTS_TOPIC_ARN = 'SNS_TENANT_EVENTS_TOPIC_ARN',
  AWS_ENDPOINT_URL = 'AWS_ENDPOINT_URL',
  AWS_REGION = 'AWS_REGION',
  AWS_ACCESS_KEY_ID = 'AWS_ACCESS_KEY_ID',
  AWS_SECRET_ACCESS_KEY = 'AWS_SECRET_ACCESS_KEY',
}
