# generated by datamodel-codegen:
#   filename:  edi-events.json
#   timestamp: 2026-07-31T07:16:40+00:00

from __future__ import annotations

from enum import Enum


class EdiEventType(Enum):
    edi_as2_partner_created = "edi.as2_partner.created"
    edi_as2_partner_updated = "edi.as2_partner.updated"
    edi_as2_partner_deleted = "edi.as2_partner.deleted"
    edi_as2_partnership_created = "edi.as2_partnership.created"
    edi_as2_partnership_updated = "edi.as2_partnership.updated"
    edi_as2_partnership_deleted = "edi.as2_partnership.deleted"
    edi_sftp_partner_created = "edi.sftp_partner.created"
    edi_sftp_partner_updated = "edi.sftp_partner.updated"
    edi_sftp_partner_deleted = "edi.sftp_partner.deleted"
    edi_inbound_route_created = "edi.inbound_route.created"
