# generated by datamodel-codegen:
#   filename:  tenant-provisioned.json
#   timestamp: 2026-07-31T07:16:40+00:00

from __future__ import annotations

from pydantic import BaseModel, Field


class TenantProvisioned(BaseModel):
    tenantId: str = Field(..., description="The unique identifier of the tenant")
    name: str = Field(..., description="The name of the tenant")
    appSlugs: list[str] = Field(..., description="List of app slugs the tenant is subscribed to")
