# generated by datamodel-codegen:
#   filename:  ucp-events.json
#   timestamp: 2026-07-31T07:16:40+00:00

from __future__ import annotations

from enum import Enum


class UcpEventType(Enum):
    tenant_provisioned = "tenant.provisioned"
    app_subscribed = "app.subscribed"
    app_unsubscribed = "app.unsubscribed"
    api_key_created = "api_key.created"
