# generated by datamodel-codegen:
#   filename:  webhook-events.json
#   timestamp: 2026-07-31T07:16:40+00:00

from __future__ import annotations

from enum import Enum


class WebhookEventType(Enum):
    webhook_created = "webhook.created"
    webhook_updated = "webhook.updated"
    webhook_deleted = "webhook.deleted"
