import logging

from fastapi import APIRouter, status

logger = logging.getLogger(__name__)
router = APIRouter(prefix="/api/v1/notifications", tags=["notifications"])

# Strict Event-Driven Architecture:
# We do not expose synchronous REST endpoints for dispatching notifications.
# The Notification engine runs as a consumer listening to the SQS queue,
# processing Domain Events generated by upstream services via their local outboxes.


@router.get("/health", status_code=status.HTTP_200_OK)
async def health_check() -> dict[str, str]:
    return {"status": "OK", "service": "notification_engine"}
