/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as TenantUsersRouteImport } from './routes/tenant/users'
import { Route as TenantRoutesRouteImport } from './routes/tenant/routes'
import { Route as TenantPartnersRouteImport } from './routes/tenant/partners'
import { Route as TenantEndpointsRouteImport } from './routes/tenant/endpoints'
import { Route as TenantEdi_toolRouteImport } from './routes/tenant/edi_tool'
import { Route as TenantDevelopersRouteImport } from './routes/tenant/developers'
import { Route as TenantDashboardRouteImport } from './routes/tenant/dashboard'
import { Route as PlatformUsersRouteImport } from './routes/platform/users'
import { Route as PlatformTenantsRouteImport } from './routes/platform/tenants'
import { Route as PlatformPartnershipsRouteImport } from './routes/platform/partnerships'
import { Route as PlatformPartnersRouteImport } from './routes/platform/partners'
import { Route as PlatformDashboardRouteImport } from './routes/platform/dashboard'

const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const TenantUsersRoute = TenantUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => TenantRoute,
} as any)
const TenantRoutesRoute = TenantRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => TenantRoute,
} as any)
const TenantPartnersRoute = TenantPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => TenantRoute,
} as any)
const TenantEndpointsRoute = TenantEndpointsRouteImport.update({
  id: '/endpoints',
  path: '/endpoints',
  getParentRoute: () => TenantRoute,
} as any)
const TenantEdi_toolRoute = TenantEdi_toolRouteImport.update({
  id: '/edi_tool',
  path: '/edi_tool',
  getParentRoute: () => TenantRoute,
} as any)
const TenantDevelopersRoute = TenantDevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => TenantRoute,
} as any)
const TenantDashboardRoute = TenantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TenantRoute,
} as any)
const PlatformUsersRoute = PlatformUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformTenantsRoute = PlatformTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformPartnershipsRoute = PlatformPartnershipsRouteImport.update({
  id: '/partnerships',
  path: '/partnerships',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformPartnersRoute = PlatformPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformDashboardRoute = PlatformDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PlatformRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/platform': typeof PlatformRouteWithChildren
  '/tenant': typeof TenantRouteWithChildren
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/partners': typeof PlatformPartnersRoute
  '/platform/partnerships': typeof PlatformPartnershipsRoute
  '/platform/tenants': typeof PlatformTenantsRoute
  '/platform/users': typeof PlatformUsersRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/developers': typeof TenantDevelopersRoute
  '/tenant/edi_tool': typeof TenantEdi_toolRoute
  '/tenant/endpoints': typeof TenantEndpointsRoute
  '/tenant/partners': typeof TenantPartnersRoute
  '/tenant/routes': typeof TenantRoutesRoute
  '/tenant/users': typeof TenantUsersRoute
}
export interface FileRoutesByTo {
  '/platform': typeof PlatformRouteWithChildren
  '/tenant': typeof TenantRouteWithChildren
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/partners': typeof PlatformPartnersRoute
  '/platform/partnerships': typeof PlatformPartnershipsRoute
  '/platform/tenants': typeof PlatformTenantsRoute
  '/platform/users': typeof PlatformUsersRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/developers': typeof TenantDevelopersRoute
  '/tenant/edi_tool': typeof TenantEdi_toolRoute
  '/tenant/endpoints': typeof TenantEndpointsRoute
  '/tenant/partners': typeof TenantPartnersRoute
  '/tenant/routes': typeof TenantRoutesRoute
  '/tenant/users': typeof TenantUsersRoute
  '/': typeof MarketingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/tenant': typeof TenantRouteWithChildren
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/partners': typeof PlatformPartnersRoute
  '/platform/partnerships': typeof PlatformPartnershipsRoute
  '/platform/tenants': typeof PlatformTenantsRoute
  '/platform/users': typeof PlatformUsersRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/developers': typeof TenantDevelopersRoute
  '/tenant/edi_tool': typeof TenantEdi_toolRoute
  '/tenant/endpoints': typeof TenantEndpointsRoute
  '/tenant/partners': typeof TenantPartnersRoute
  '/tenant/routes': typeof TenantRoutesRoute
  '/tenant/users': typeof TenantUsersRoute
  '/_marketing/': typeof MarketingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/platform'
    | '/tenant'
    | '/platform/dashboard'
    | '/platform/partners'
    | '/platform/partnerships'
    | '/platform/tenants'
    | '/platform/users'
    | '/tenant/dashboard'
    | '/tenant/developers'
    | '/tenant/edi_tool'
    | '/tenant/endpoints'
    | '/tenant/partners'
    | '/tenant/routes'
    | '/tenant/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/platform'
    | '/tenant'
    | '/platform/dashboard'
    | '/platform/partners'
    | '/platform/partnerships'
    | '/platform/tenants'
    | '/platform/users'
    | '/tenant/dashboard'
    | '/tenant/developers'
    | '/tenant/edi_tool'
    | '/tenant/endpoints'
    | '/tenant/partners'
    | '/tenant/routes'
    | '/tenant/users'
    | '/'
  id:
    | '__root__'
    | '/_marketing'
    | '/platform'
    | '/tenant'
    | '/platform/dashboard'
    | '/platform/partners'
    | '/platform/partnerships'
    | '/platform/tenants'
    | '/platform/users'
    | '/tenant/dashboard'
    | '/tenant/developers'
    | '/tenant/edi_tool'
    | '/tenant/endpoints'
    | '/tenant/partners'
    | '/tenant/routes'
    | '/tenant/users'
    | '/_marketing/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
  TenantRoute: typeof TenantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/tenant/users': {
      id: '/tenant/users'
      path: '/users'
      fullPath: '/tenant/users'
      preLoaderRoute: typeof TenantUsersRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/routes': {
      id: '/tenant/routes'
      path: '/routes'
      fullPath: '/tenant/routes'
      preLoaderRoute: typeof TenantRoutesRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/partners': {
      id: '/tenant/partners'
      path: '/partners'
      fullPath: '/tenant/partners'
      preLoaderRoute: typeof TenantPartnersRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/endpoints': {
      id: '/tenant/endpoints'
      path: '/endpoints'
      fullPath: '/tenant/endpoints'
      preLoaderRoute: typeof TenantEndpointsRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/edi_tool': {
      id: '/tenant/edi_tool'
      path: '/edi_tool'
      fullPath: '/tenant/edi_tool'
      preLoaderRoute: typeof TenantEdi_toolRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/developers': {
      id: '/tenant/developers'
      path: '/developers'
      fullPath: '/tenant/developers'
      preLoaderRoute: typeof TenantDevelopersRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/dashboard': {
      id: '/tenant/dashboard'
      path: '/dashboard'
      fullPath: '/tenant/dashboard'
      preLoaderRoute: typeof TenantDashboardRouteImport
      parentRoute: typeof TenantRoute
    }
    '/platform/users': {
      id: '/platform/users'
      path: '/users'
      fullPath: '/platform/users'
      preLoaderRoute: typeof PlatformUsersRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/tenants': {
      id: '/platform/tenants'
      path: '/tenants'
      fullPath: '/platform/tenants'
      preLoaderRoute: typeof PlatformTenantsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/partnerships': {
      id: '/platform/partnerships'
      path: '/partnerships'
      fullPath: '/platform/partnerships'
      preLoaderRoute: typeof PlatformPartnershipsRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/partners': {
      id: '/platform/partners'
      path: '/partners'
      fullPath: '/platform/partners'
      preLoaderRoute: typeof PlatformPartnersRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/dashboard': {
      id: '/platform/dashboard'
      path: '/dashboard'
      fullPath: '/platform/dashboard'
      preLoaderRoute: typeof PlatformDashboardRouteImport
      parentRoute: typeof PlatformRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface PlatformRouteChildren {
  PlatformDashboardRoute: typeof PlatformDashboardRoute
  PlatformPartnersRoute: typeof PlatformPartnersRoute
  PlatformPartnershipsRoute: typeof PlatformPartnershipsRoute
  PlatformTenantsRoute: typeof PlatformTenantsRoute
  PlatformUsersRoute: typeof PlatformUsersRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformDashboardRoute: PlatformDashboardRoute,
  PlatformPartnersRoute: PlatformPartnersRoute,
  PlatformPartnershipsRoute: PlatformPartnershipsRoute,
  PlatformTenantsRoute: PlatformTenantsRoute,
  PlatformUsersRoute: PlatformUsersRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

interface TenantRouteChildren {
  TenantDashboardRoute: typeof TenantDashboardRoute
  TenantDevelopersRoute: typeof TenantDevelopersRoute
  TenantEdi_toolRoute: typeof TenantEdi_toolRoute
  TenantEndpointsRoute: typeof TenantEndpointsRoute
  TenantPartnersRoute: typeof TenantPartnersRoute
  TenantRoutesRoute: typeof TenantRoutesRoute
  TenantUsersRoute: typeof TenantUsersRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantDashboardRoute: TenantDashboardRoute,
  TenantDevelopersRoute: TenantDevelopersRoute,
  TenantEdi_toolRoute: TenantEdi_toolRoute,
  TenantEndpointsRoute: TenantEndpointsRoute,
  TenantPartnersRoute: TenantPartnersRoute,
  TenantRoutesRoute: TenantRoutesRoute,
  TenantUsersRoute: TenantUsersRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
  TenantRoute: TenantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
