"""initial_schema

Revision ID: 4741975849db
Revises:
Create Date: 2026-08-06 16:26:20.679946

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4741975849db"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "as2_partners",
        sa.Column("tenant_id", sa.String(length=128), nullable=True),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("as2_id", sa.String(length=255), nullable=False),
        sa.Column("public_cert_pem", sa.Text(), nullable=True),
        sa.Column("public_cert_vault_ref", sa.String(length=255), nullable=True),
        sa.Column("private_key_vault_ref", sa.String(length=255), nullable=True),
        sa.Column("prev_public_cert_pem", sa.Text(), nullable=True),
        sa.Column("prev_public_cert_vault_ref", sa.String(length=255), nullable=True),
        sa.Column("prev_private_key_vault_ref", sa.String(length=255), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("is_local", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "as2_id", name="uq_tenant_as2_id"),
        schema="edi",
    )
    op.create_index(
        op.f("ix_edi_as2_partners_tenant_id"),
        "as2_partners",
        ["tenant_id"],
        unique=False,
        schema="edi",
    )
    op.create_index(
        "uq_global_as2_id",
        "as2_partners",
        ["as2_id"],
        unique=True,
        schema="edi",
        postgresql_where=sa.text("tenant_id IS NULL"),
    )
    op.create_table(
        "outbound_edi_headers",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("trading_partner_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("isa_sender_id", sa.String(length=255), nullable=False),
        sa.Column("isa_sender_qualifier", sa.String(length=2), nullable=True),
        sa.Column("isa_receiver_id", sa.String(length=255), nullable=False),
        sa.Column("isa_receiver_qualifier", sa.String(length=2), nullable=True),
        sa.Column("gs_sender_id", sa.String(length=255), nullable=False),
        sa.Column("gs_receiver_id", sa.String(length=255), nullable=False),
        sa.Column("transaction_type", sa.String(length=50), nullable=False),
        sa.Column("default_standard", sa.String(length=50), server_default="x12", nullable=False),
        sa.Column("default_version", sa.String(length=50), server_default="004010", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="edi",
    )
    op.create_index(
        op.f("ix_edi_outbound_edi_headers_deleted_at"),
        "outbound_edi_headers",
        ["deleted_at"],
        unique=False,
        schema="edi",
    )
    op.create_index(
        op.f("ix_edi_outbound_edi_headers_tenant_id"),
        "outbound_edi_headers",
        ["tenant_id"],
        unique=False,
        schema="edi",
    )
    op.create_index(
        "ix_outbound_edi_headers_unique_trading_partner_id",
        "outbound_edi_headers",
        ["tenant_id", "trading_partner_id"],
        unique=True,
        schema="edi",
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("owner_token", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
        schema="edi",
    )
    op.create_index(
        op.f("ix_edi_outbox_tenant_id"), "outbox", ["tenant_id"], unique=False, schema="edi"
    )
    op.create_index(
        "ix_global_outbox_pending",
        "outbox",
        ["status", "created_at"],
        unique=False,
        schema="edi",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "sftp_partners",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("host", sa.String(length=1024), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("host_key", sa.Text(), nullable=True),
        sa.Column("inbound_remote_path", sa.String(length=1024), nullable=True),
        sa.Column("outbound_remote_path", sa.String(length=1024), nullable=True),
        sa.Column("password_encrypted", sa.String(length=1024), nullable=True),
        sa.Column("credentials_vault_ref", sa.String(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        schema="edi",
    )
    op.create_index(
        op.f("ix_edi_sftp_partners_deleted_at"),
        "sftp_partners",
        ["deleted_at"],
        unique=False,
        schema="edi",
    )
    op.create_index(
        op.f("ix_edi_sftp_partners_tenant_id"),
        "sftp_partners",
        ["tenant_id"],
        unique=False,
        schema="edi",
    )
    op.create_table(
        "as2_partnerships",
        sa.Column("tenant_id", sa.String(length=128), nullable=True),
        sa.Column("local_partner_id", sa.String(length=128), nullable=False),
        sa.Column("remote_partner_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("credentials_vault_ref", sa.String(length=255), nullable=True),
        sa.Column("mdn_type", sa.String(length=50), nullable=False),
        sa.Column("mdn_url", sa.String(length=1024), nullable=True),
        sa.Column("encryption_algorithm", sa.String(length=50), nullable=False),
        sa.Column("signature_algorithm", sa.String(length=50), nullable=False),
        sa.Column("advanced_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["local_partner_id"], ["edi.as2_partners.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["remote_partner_id"], ["edi.as2_partners.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("local_partner_id", "remote_partner_id", name="uq_as2_partnership"),
        schema="edi",
    )
    op.create_table(
        "inbound_routes",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("webhook_id", sa.String(length=128), nullable=True),
        sa.Column("as2_partner_id", sa.String(length=128), nullable=True),
        sa.Column("sftp_partner_id", sa.String(length=128), nullable=True),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("trading_partner_id", sa.String(length=255), nullable=True),
        sa.Column("isa_sender_id", sa.String(length=255), nullable=False),
        sa.Column("isa_receiver_id", sa.String(length=255), nullable=False),
        sa.Column("gs_sender_id", sa.String(length=255), nullable=True),
        sa.Column("gs_receiver_id", sa.String(length=255), nullable=True),
        sa.Column("transaction_type", sa.String(length=50), nullable=False),
        sa.Column(
            "processing_mode", sa.String(length=50), server_default="TRANSFORM", nullable=False
        ),
        sa.Column("active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "(webhook_id IS NOT NULL)::int + (as2_partner_id IS NOT NULL)::int + (sftp_partner_id IS NOT NULL)::int = 1",
            name="chk_inbound_routes_exactly_one_dest",
        ),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["ucp.webhooks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["as2_partner_id"],
            ["edi.as2_partners.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sftp_partner_id"],
            ["edi.sftp_partners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="edi",
    )
    op.create_index(
        op.f("ix_edi_inbound_routes_deleted_at"),
        "inbound_routes",
        ["deleted_at"],
        unique=False,
        schema="edi",
    )
    op.create_index(
        op.f("ix_edi_inbound_routes_tenant_id"),
        "inbound_routes",
        ["tenant_id"],
        unique=False,
        schema="edi",
    )
    op.create_index(
        "ix_inbound_routes_unique_active",
        "inbound_routes",
        ["tenant_id", "isa_sender_id", "isa_receiver_id", "transaction_type"],
        unique=True,
        schema="edi",
        postgresql_where=sa.text("active = true"),
    )
    op.create_table(
        "outbound_routes",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("as2_partner_id", sa.String(length=128), nullable=True),
        sa.Column("sftp_partner_id", sa.String(length=128), nullable=True),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("trading_partner_id", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("protocol", sa.String(length=50), server_default="AS2", nullable=False),
        sa.Column("active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("deleted_by", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "(as2_partner_id IS NOT NULL)::int + (sftp_partner_id IS NOT NULL)::int = 1",
            name="chk_outbound_routes_exactly_one_dest",
        ),
        sa.ForeignKeyConstraint(
            ["as2_partner_id"],
            ["edi.as2_partners.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sftp_partner_id"],
            ["edi.sftp_partners.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="edi",
    )
    op.create_index(
        op.f("ix_edi_outbound_routes_deleted_at"),
        "outbound_routes",
        ["deleted_at"],
        unique=False,
        schema="edi",
    )
    op.create_index(
        op.f("ix_edi_outbound_routes_tenant_id"),
        "outbound_routes",
        ["tenant_id"],
        unique=False,
        schema="edi",
    )
    op.create_index(
        "ix_outbound_routes_unique_trading_partner_id",
        "outbound_routes",
        ["tenant_id", "trading_partner_id"],
        unique=True,
        schema="edi",
        postgresql_where=sa.text("active = true"),
    )

    # --- Custom Postgres Triggers for Transactional Outbox ---
    op.execute("""
        CREATE OR REPLACE FUNCTION edi_outbox_notify() RETURNS trigger AS $$
        BEGIN
            PERFORM pg_notify('edi_outbox_channel', NEW.id);
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute("""
        CREATE TRIGGER trg_edi_outbox_notify
        AFTER INSERT ON edi.outbox
        FOR EACH ROW EXECUTE FUNCTION edi_outbox_notify();
    """)
    # ---------------------------------------------------------------------------
    # Soft Delete enabled natively in table definitions.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # --- Drop Custom Postgres Triggers ---
    op.execute("DROP TRIGGER IF EXISTS trg_edi_outbox_notify ON edi.outbox;")
    op.execute("DROP FUNCTION IF EXISTS edi_outbox_notify();")

    op.drop_index(
        "ix_outbound_routes_unique_trading_partner_id",
        table_name="outbound_routes",
        schema="edi",
        postgresql_where=sa.text("active = true"),
    )
    op.drop_index(
        op.f("ix_edi_outbound_routes_tenant_id"), table_name="outbound_routes", schema="edi"
    )
    op.drop_table("outbound_routes", schema="edi")
    op.drop_index(
        "ix_inbound_routes_unique_active",
        table_name="inbound_routes",
        schema="edi",
        postgresql_where=sa.text("active = true"),
    )
    op.drop_index(
        op.f("ix_edi_inbound_routes_tenant_id"), table_name="inbound_routes", schema="edi"
    )
    op.drop_table("inbound_routes", schema="edi")
    op.drop_table("as2_partnerships", schema="edi")
    op.drop_index(op.f("ix_edi_sftp_partners_tenant_id"), table_name="sftp_partners", schema="edi")
    op.drop_table("sftp_partners", schema="edi")
    op.drop_index(
        "ix_global_outbox_pending",
        table_name="outbox",
        schema="edi",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_index(op.f("ix_edi_outbox_tenant_id"), table_name="outbox", schema="edi")
    op.drop_table("outbox", schema="edi")
    op.drop_index(
        "ix_outbound_edi_headers_unique_trading_partner_id",
        table_name="outbound_edi_headers",
        schema="edi",
    )
    op.drop_index(
        op.f("ix_edi_outbound_edi_headers_tenant_id"),
        table_name="outbound_edi_headers",
        schema="edi",
    )
    op.drop_table("outbound_edi_headers", schema="edi")
    op.drop_index(
        "uq_global_as2_id",
        table_name="as2_partners",
        schema="edi",
        postgresql_where=sa.text("tenant_id IS NULL"),
    )
    op.drop_index(op.f("ix_edi_as2_partners_tenant_id"), table_name="as2_partners", schema="edi")
    op.drop_table("as2_partners", schema="edi")
    # ### end Alembic commands ###
