"""empty message

Revision ID: 16071c55d650
Revises: f5a0418c26a5
Create Date: 2026-08-20 15:33:23.549899

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '16071c55d650'
down_revision: str | Sequence[str] | None = 'f5a0418c26a5'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_identity_api_keys_deleted_at'), table_name='api_keys', schema='identity')
    op.drop_index(op.f('ix_identity_api_tokens_deleted_at'), table_name='api_tokens', schema='identity')
    op.drop_index(op.f('ix_identity_roles_deleted_at'), table_name='roles', schema='identity')
    op.drop_index(op.f('ix_identity_tenants_deleted_at'), table_name='tenants', schema='identity')
    op.drop_index(op.f('ix_identity_users_deleted_at'), table_name='users', schema='identity')
    op.create_index('idx_app_subs_tenant_status', 'app_subscriptions', ['tenant_id', 'status'], unique=False, schema='ucp')
    op.drop_index(op.f('ix_ucp_webhooks_deleted_at'), table_name='webhooks', schema='ucp')
    op.alter_column('scheduled_jobs', 'retry_count', schema='scheduling', server_default='0')
    op.alter_column('scheduled_jobs', 'max_retries', schema='scheduling', server_default='3')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_ucp_webhooks_deleted_at'), 'webhooks', ['deleted_at'], unique=False, schema='ucp')
    op.drop_index('idx_app_subs_tenant_status', table_name='app_subscriptions', schema='ucp')
    op.create_index(op.f('ix_identity_users_deleted_at'), 'users', ['deleted_at'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_tenants_deleted_at'), 'tenants', ['deleted_at'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_roles_deleted_at'), 'roles', ['deleted_at'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_api_tokens_deleted_at'), 'api_tokens', ['deleted_at'], unique=False, schema='identity')
    op.create_index(op.f('ix_identity_api_keys_deleted_at'), 'api_keys', ['deleted_at'], unique=False, schema='identity')
    op.alter_column('scheduled_jobs', 'max_retries', schema='scheduling', server_default=None)
    op.alter_column('scheduled_jobs', 'retry_count', schema='scheduling', server_default=None)
    # ### end Alembic commands ###
