"""add severity to in app notifications

Revision ID: 39a39b965162
Revises: 843b3e309769
Create Date: 2026-08-11 22:35:38.786355

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "39a39b965162"
down_revision: str | Sequence[str] | None = "843b3e309769"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        "in_app_notifications",
        sa.Column("severity", sa.String(length=50), server_default="info", nullable=False),
        schema="notifications",
    )
    op.drop_index(
        op.f("ix_in_app_notif_tenant_user_read"),
        table_name="in_app_notifications",
        schema="notifications",
    )
    op.create_index(
        "ix_in_app_notif_tenant_user_read",
        "in_app_notifications",
        ["tenant_id", "user_id", "is_read", "created_at"],
        unique=False,
        schema="notifications",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_in_app_notif_tenant_user_read",
        table_name="in_app_notifications",
        schema="notifications",
    )
    op.create_index(
        op.f("ix_in_app_notif_tenant_user_read"),
        "in_app_notifications",
        ["tenant_id", "user_id", "is_read"],
        unique=False,
        schema="notifications",
    )
    op.drop_column("in_app_notifications", "severity", schema="notifications")
    # ### end Alembic commands ###
