"""Initial schema

Revision ID: 699ca3b82d04
Revises: 
Create Date: 2026-08-05 11:20:25.971040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '699ca3b82d04'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('as2_partners',
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('as2_id', sa.String(length=255), nullable=False),
    sa.Column('public_cert_pem', sa.Text(), nullable=True),
    sa.Column('public_cert_vault_ref', sa.String(length=255), nullable=True),
    sa.Column('private_key_vault_ref', sa.String(length=255), nullable=True),
    sa.Column('prev_public_cert_pem', sa.Text(), nullable=True),
    sa.Column('prev_public_cert_vault_ref', sa.String(length=255), nullable=True),
    sa.Column('prev_private_key_vault_ref', sa.String(length=255), nullable=True),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('is_local', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'as2_id', name='uq_tenant_as2_id'),
    schema='edi'
    )
    op.create_index(op.f('ix_edi_as2_partners_tenant_id'), 'as2_partners', ['tenant_id'], unique=False, schema='edi')
    op.create_index('uq_global_as2_id', 'as2_partners', ['as2_id'], unique=True, schema='edi', postgresql_where=sa.text('tenant_id IS NULL'))
    op.create_table('outbound_edi_headers',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('trading_partner_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('isa_sender_id', sa.String(length=255), nullable=False),
    sa.Column('isa_sender_qualifier', sa.String(length=2), nullable=True),
    sa.Column('isa_receiver_id', sa.String(length=255), nullable=False),
    sa.Column('isa_receiver_qualifier', sa.String(length=2), nullable=True),
    sa.Column('gs_sender_id', sa.String(length=255), nullable=False),
    sa.Column('gs_receiver_id', sa.String(length=255), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('default_standard', sa.String(length=50), server_default='x12', nullable=False),
    sa.Column('default_version', sa.String(length=50), server_default='004010', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='edi'
    )
    op.create_index(op.f('ix_edi_outbound_edi_headers_tenant_id'), 'outbound_edi_headers', ['tenant_id'], unique=False, schema='edi')
    op.create_index('ix_outbound_edi_headers_unique_trading_partner_id', 'outbound_edi_headers', ['tenant_id', 'trading_partner_id'], unique=True, schema='edi')
    op.create_table('outbox',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_token', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    schema='edi'
    )
    op.create_index(op.f('ix_edi_outbox_tenant_id'), 'outbox', ['tenant_id'], unique=False, schema='edi')
    op.create_index('ix_global_outbox_pending', 'outbox', ['status', 'created_at'], unique=False, schema='edi', postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('sftp_partners',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=1024), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('host_key', sa.Text(), nullable=True),
    sa.Column('inbound_remote_path', sa.String(length=1024), nullable=True),
    sa.Column('outbound_remote_path', sa.String(length=1024), nullable=True),
    sa.Column('password_encrypted', sa.String(length=1024), nullable=True),
    sa.Column('credentials_vault_ref', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='edi'
    )
    op.create_index(op.f('ix_edi_sftp_partners_tenant_id'), 'sftp_partners', ['tenant_id'], unique=False, schema='edi')
    op.create_table('apps',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug'),
    schema='ucp'
    )
    op.create_table('database_shards',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('dsn', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='ucp'
    )
    op.create_table('outbox',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner_token', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key'),
    schema='ucp'
    )
    op.create_index('ix_global_outbox_pending', 'outbox', ['status', 'created_at'], unique=False, schema='ucp', postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('platform_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key'),
    schema='ucp'
    )
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('target_queue', sa.String(), nullable=True),
    sa.Column('app_namespace', sa.String(), nullable=True),
    sa.Column('cron_expression', sa.String(), nullable=True),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.String(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('min_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('max_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ucp'
    )
    op.create_index(op.f('ix_ucp_scheduled_jobs_name'), 'scheduled_jobs', ['name'], unique=False, schema='ucp')
    op.create_index(op.f('ix_ucp_scheduled_jobs_next_run_at'), 'scheduled_jobs', ['next_run_at'], unique=False, schema='ucp')
    op.create_index(op.f('ix_ucp_scheduled_jobs_status'), 'scheduled_jobs', ['status'], unique=False, schema='ucp')
    op.create_table('system_audit_log',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('trace_id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('event', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ucp'
    )
    op.create_index('ix_system_audit_log_tenant_time', 'system_audit_log', ['tenant_id', 'created_at'], unique=False, schema='ucp')
    op.create_index(op.f('ix_ucp_system_audit_log_trace_id'), 'system_audit_log', ['trace_id'], unique=False, schema='ucp')
    op.create_table('tenants',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('idp_tenant_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idp_tenant_id'),
    sa.UniqueConstraint('name'),
    schema='ucp'
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('idp_user_id', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idp_user_id'),
    schema='ucp'
    )
    op.create_index('uq_users_email_lower', 'users', [sa.literal_column('lower(email)')], unique=True, schema='ucp')
    op.create_table('webhooks',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('auth_header_vault_ref', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='ucp'
    )
    op.create_index(op.f('ix_ucp_webhooks_tenant_id'), 'webhooks', ['tenant_id'], unique=False, schema='ucp')
    op.create_table('as2_partnerships',
    sa.Column('tenant_id', sa.String(length=128), nullable=True),
    sa.Column('local_partner_id', sa.String(length=128), nullable=False),
    sa.Column('remote_partner_id', sa.String(length=128), nullable=False),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('credentials_vault_ref', sa.String(length=255), nullable=True),
    sa.Column('mdn_type', sa.String(length=50), nullable=False),
    sa.Column('mdn_url', sa.String(length=1024), nullable=True),
    sa.Column('encryption_algorithm', sa.String(length=50), nullable=False),
    sa.Column('signature_algorithm', sa.String(length=50), nullable=False),
    sa.Column('advanced_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['local_partner_id'], ['edi.as2_partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['remote_partner_id'], ['edi.as2_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('local_partner_id', 'remote_partner_id', name='uq_as2_partnership'),
    schema='edi'
    )
    op.create_table('inbound_routes',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('webhook_id', sa.String(length=128), nullable=True),
    sa.Column('as2_partner_id', sa.String(length=128), nullable=True),
    sa.Column('sftp_partner_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('trading_partner_id', sa.String(length=255), nullable=True),
    sa.Column('isa_sender_id', sa.String(length=255), nullable=False),
    sa.Column('isa_receiver_id', sa.String(length=255), nullable=False),
    sa.Column('gs_sender_id', sa.String(length=255), nullable=True),
    sa.Column('gs_receiver_id', sa.String(length=255), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('processing_mode', sa.String(length=50), server_default='TRANSFORM', nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(webhook_id IS NOT NULL)::int + (as2_partner_id IS NOT NULL)::int + (sftp_partner_id IS NOT NULL)::int = 1', name='chk_inbound_routes_exactly_one_dest'),
    sa.ForeignKeyConstraint(['as2_partner_id'], ['edi.as2_partners.id'], ),
    sa.ForeignKeyConstraint(['sftp_partner_id'], ['edi.sftp_partners.id'], ),
    sa.ForeignKeyConstraint(['webhook_id'], ['ucp.webhooks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='edi'
    )
    op.create_index(op.f('ix_edi_inbound_routes_tenant_id'), 'inbound_routes', ['tenant_id'], unique=False, schema='edi')
    op.create_index('ix_inbound_routes_unique_active', 'inbound_routes', ['tenant_id', 'isa_sender_id', 'isa_receiver_id', 'transaction_type'], unique=True, schema='edi', postgresql_where=sa.text('active = true'))
    op.create_table('outbound_routes',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('as2_partner_id', sa.String(length=128), nullable=True),
    sa.Column('sftp_partner_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('trading_partner_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('protocol', sa.String(length=50), server_default='AS2', nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(as2_partner_id IS NOT NULL)::int + (sftp_partner_id IS NOT NULL)::int = 1', name='chk_outbound_routes_exactly_one_dest'),
    sa.ForeignKeyConstraint(['as2_partner_id'], ['edi.as2_partners.id'], ),
    sa.ForeignKeyConstraint(['sftp_partner_id'], ['edi.sftp_partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='edi'
    )
    op.create_index(op.f('ix_edi_outbound_routes_tenant_id'), 'outbound_routes', ['tenant_id'], unique=False, schema='edi')
    op.create_index('ix_outbound_routes_unique_trading_partner_id', 'outbound_routes', ['tenant_id', 'trading_partner_id'], unique=True, schema='edi', postgresql_where=sa.text('active = true'))
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['ucp.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    schema='ucp'
    )
    op.create_index(op.f('ix_ucp_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False, schema='ucp')
    op.create_table('api_tokens',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.String(length=64), nullable=False),
    sa.Column('secret_hash', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['ucp.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id'),
    schema='ucp'
    )
    op.create_index(op.f('ix_ucp_api_tokens_tenant_id'), 'api_tokens', ['tenant_id'], unique=False, schema='ucp')
    op.create_table('app_subscriptions',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('app_id', sa.String(length=128), nullable=False),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['ucp.apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['ucp.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'app_id'),
    schema='ucp'
    )
    op.create_table('shard_registry',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('app_id', sa.String(length=128), nullable=False),
    sa.Column('shard_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['ucp.apps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shard_id'], ['ucp.database_shards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['ucp.tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'app_id'),
    schema='ucp'
    )
    op.create_table('tenant_users',
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['ucp.tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['ucp.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id', 'user_id'),
    schema='ucp'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_users', schema='ucp')
    op.drop_table('shard_registry', schema='ucp')
    op.drop_table('app_subscriptions', schema='ucp')
    op.drop_index(op.f('ix_ucp_api_tokens_tenant_id'), table_name='api_tokens', schema='ucp')
    op.drop_table('api_tokens', schema='ucp')
    op.drop_index(op.f('ix_ucp_api_keys_tenant_id'), table_name='api_keys', schema='ucp')
    op.drop_table('api_keys', schema='ucp')
    op.drop_index('ix_outbound_routes_unique_trading_partner_id', table_name='outbound_routes', schema='edi', postgresql_where=sa.text('active = true'))
    op.drop_index(op.f('ix_edi_outbound_routes_tenant_id'), table_name='outbound_routes', schema='edi')
    op.drop_table('outbound_routes', schema='edi')
    op.drop_index('ix_inbound_routes_unique_active', table_name='inbound_routes', schema='edi', postgresql_where=sa.text('active = true'))
    op.drop_index(op.f('ix_edi_inbound_routes_tenant_id'), table_name='inbound_routes', schema='edi')
    op.drop_table('inbound_routes', schema='edi')
    op.drop_table('as2_partnerships', schema='edi')
    op.drop_index(op.f('ix_ucp_webhooks_tenant_id'), table_name='webhooks', schema='ucp')
    op.drop_table('webhooks', schema='ucp')
    op.drop_index('uq_users_email_lower', table_name='users', schema='ucp')
    op.drop_table('users', schema='ucp')
    op.drop_table('tenants', schema='ucp')
    op.drop_index(op.f('ix_ucp_system_audit_log_trace_id'), table_name='system_audit_log', schema='ucp')
    op.drop_index('ix_system_audit_log_tenant_time', table_name='system_audit_log', schema='ucp')
    op.drop_table('system_audit_log', schema='ucp')
    op.drop_index(op.f('ix_ucp_scheduled_jobs_status'), table_name='scheduled_jobs', schema='ucp')
    op.drop_index(op.f('ix_ucp_scheduled_jobs_next_run_at'), table_name='scheduled_jobs', schema='ucp')
    op.drop_index(op.f('ix_ucp_scheduled_jobs_name'), table_name='scheduled_jobs', schema='ucp')
    op.drop_table('scheduled_jobs', schema='ucp')
    op.drop_table('platform_settings', schema='ucp')
    op.drop_index('ix_global_outbox_pending', table_name='outbox', schema='ucp', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_table('outbox', schema='ucp')
    op.drop_table('database_shards', schema='ucp')
    op.drop_table('apps', schema='ucp')
    op.drop_index(op.f('ix_edi_sftp_partners_tenant_id'), table_name='sftp_partners', schema='edi')
    op.drop_table('sftp_partners', schema='edi')
    op.drop_index('ix_global_outbox_pending', table_name='outbox', schema='edi', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_edi_outbox_tenant_id'), table_name='outbox', schema='edi')
    op.drop_table('outbox', schema='edi')
    op.drop_index('ix_outbound_edi_headers_unique_trading_partner_id', table_name='outbound_edi_headers', schema='edi')
    op.drop_index(op.f('ix_edi_outbound_edi_headers_tenant_id'), table_name='outbound_edi_headers', schema='edi')
    op.drop_table('outbound_edi_headers', schema='edi')
    op.drop_index('uq_global_as2_id', table_name='as2_partners', schema='edi', postgresql_where=sa.text('tenant_id IS NULL'))
    op.drop_index(op.f('ix_edi_as2_partners_tenant_id'), table_name='as2_partners', schema='edi')
    op.drop_table('as2_partners', schema='edi')
    # ### end Alembic commands ###
