"""Initial schema

Revision ID: f5a0418c26a5
Revises:
Create Date: 2026-08-13 23:52:48.108189

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f5a0418c26a5"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "platform_settings",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
        schema="identity",
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("idp_tenant_id", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idp_tenant_id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
        schema="identity",
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("idp_user_id", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idp_user_id"),
        schema="identity",
    )
    op.create_index(
        "uq_users_email_lower",
        "users",
        [sa.literal_column("lower(email)")],
        unique=True,
        schema="identity",
    )
    op.create_table(
        "notification_outbox",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("owner_token", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
        schema="notifications",
    )
    op.create_index(
        "ix_notif_outbox_pending",
        "notification_outbox",
        ["status", "created_at"],
        unique=False,
        schema="notifications",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "system_audit_log",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("event", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="observability",
    )
    op.create_index(
        op.f("ix_observability_system_audit_log_trace_id"),
        "system_audit_log",
        ["trace_id"],
        unique=False,
        schema="observability",
    )
    op.create_index(
        "ix_system_audit_log_tenant_time",
        "system_audit_log",
        ["tenant_id", "created_at"],
        unique=False,
        schema="observability",
    )
    op.create_table(
        "scheduled_jobs",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("next_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("interval_seconds", sa.Integer(), nullable=True),
        sa.Column("min_interval_seconds", sa.Integer(), nullable=True),
        sa.Column("max_interval_seconds", sa.Integer(), nullable=True),
        sa.Column("cron_expression", sa.String(length=100), nullable=True),
        sa.Column("timezone", sa.String(length=50), nullable=True),
        sa.Column("target_queue", sa.String(length=255), nullable=True),
        sa.Column("app_namespace", sa.String(length=255), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("owner_token", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="scheduling",
    )
    op.create_index(
        "job_status_next_run_idx",
        "scheduled_jobs",
        ["status", "next_run_at"],
        unique=False,
        schema="scheduling",
    )
    op.create_table(
        "apps",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("slug", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
        schema="ucp",
    )
    op.create_table(
        "database_shards",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("dsn", sa.String(length=1024), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        schema="ucp",
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("owner_token", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
        schema="ucp",
    )
    op.create_index(
        "ix_global_outbox_pending",
        "outbox",
        ["status", "created_at"],
        unique=False,
        schema="ucp",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "webhooks",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("auth_header_vault_ref", sa.String(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="ucp",
    )
    op.create_index(
        op.f("ix_ucp_webhooks_tenant_id"), "webhooks", ["tenant_id"], unique=False, schema="ucp"
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("key_hash", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("scopes", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["identity.tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_hash"),
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_api_keys_tenant_id"),
        "api_keys",
        ["tenant_id"],
        unique=False,
        schema="identity",
    )
    op.create_table(
        "api_tokens",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("client_id", sa.String(length=64), nullable=False),
        sa.Column("secret_hash", sa.String(length=64), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["identity.tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("client_id"),
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_api_tokens_tenant_id"),
        "api_tokens",
        ["tenant_id"],
        unique=False,
        schema="identity",
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("capabilities", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["identity.tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="identity",
    )
    op.create_index(
        op.f("ix_identity_roles_tenant_id"), "roles", ["tenant_id"], unique=False, schema="identity"
    )
    op.create_index(
        "uix_roles_tenant_name",
        "roles",
        ["tenant_id", "name"],
        unique=True,
        schema="identity",
        postgresql_nulls_not_distinct=True,
    )
    op.create_table(
        "tenant_users",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.Column("active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["identity.tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["identity.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant_id", "user_id"),
        schema="identity",
    )
    op.create_table(
        "in_app_notifications",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=50), server_default="info", nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["identity.tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["identity.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="notifications",
    )
    op.create_index(
        "ix_in_app_notif_tenant_user_read",
        "in_app_notifications",
        ["tenant_id", "user_id", "is_read", "created_at"],
        unique=False,
        schema="notifications",
    )
    op.create_table(
        "notification_route_configurations",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column(
            "channels", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("destination_config", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["identity.tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "event_type", name="notification_route_idx"),
        schema="notifications",
    )
    op.create_table(
        "notification_templates",
        sa.Column("id", sa.String(length=128), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("channel", sa.String(length=50), nullable=False),
        sa.Column("subject_template", sa.Text(), nullable=True),
        sa.Column("body_template", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["identity.tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "event_type", "channel", name="notification_template_idx"),
        schema="notifications",
    )
    op.create_table(
        "user_notification_preferences",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("channel", sa.String(length=50), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["identity.tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["identity.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "user_id", "event_type", "channel", name="user_notif_pref_idx"
        ),
        schema="notifications",
    )
    op.create_table(
        "app_subscriptions",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("app_id", sa.String(length=128), nullable=False),
        sa.Column("tier", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["app_id"], ["ucp.apps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["identity.tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant_id", "app_id"),
        schema="ucp",
    )
    op.create_table(
        "shard_registry",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("app_id", sa.String(length=128), nullable=False),
        sa.Column("shard_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["app_id"], ["ucp.apps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["shard_id"], ["ucp.database_shards.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["identity.tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("tenant_id", "app_id"),
        schema="ucp",
    )
    op.create_table(
        "user_roles",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=True),
        sa.Column("user_id", sa.String(length=128), nullable=False),
        sa.Column("role_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["identity.roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["identity.tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["identity.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="identity",
    )
    op.create_index(
        "uix_user_roles_tenant_user_role",
        "user_roles",
        ["tenant_id", "user_id", "role_id"],
        unique=True,
        schema="identity",
        postgresql_nulls_not_distinct=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles", schema="identity")
    op.drop_table("shard_registry", schema="ucp")
    op.drop_table("app_subscriptions", schema="ucp")
    op.drop_table("user_notification_preferences", schema="notifications")
    op.drop_table("notification_templates", schema="notifications")
    op.drop_table("notification_route_configurations", schema="notifications")
    op.drop_index(
        "ix_in_app_notif_tenant_user_read",
        table_name="in_app_notifications",
        schema="notifications",
    )
    op.drop_table("in_app_notifications", schema="notifications")
    op.drop_table("tenant_users", schema="identity")
    op.drop_index(op.f("ix_identity_roles_tenant_id"), table_name="roles", schema="identity")
    op.drop_table("roles", schema="identity")
    op.drop_index(
        op.f("ix_identity_api_tokens_tenant_id"), table_name="api_tokens", schema="identity"
    )
    op.drop_table("api_tokens", schema="identity")
    op.drop_index(op.f("ix_identity_api_keys_tenant_id"), table_name="api_keys", schema="identity")
    op.drop_table("api_keys", schema="identity")
    op.drop_index(op.f("ix_ucp_webhooks_tenant_id"), table_name="webhooks", schema="ucp")
    op.drop_table("webhooks", schema="ucp")
    op.drop_index(
        "ix_global_outbox_pending",
        table_name="outbox",
        schema="ucp",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_table("outbox", schema="ucp")
    op.drop_table("database_shards", schema="ucp")
    op.drop_table("apps", schema="ucp")
    op.drop_index("job_status_next_run_idx", table_name="scheduled_jobs", schema="scheduling")
    op.drop_table("scheduled_jobs", schema="scheduling")
    op.drop_index(
        "ix_system_audit_log_tenant_time", table_name="system_audit_log", schema="observability"
    )
    op.drop_index(
        op.f("ix_observability_system_audit_log_trace_id"),
        table_name="system_audit_log",
        schema="observability",
    )
    op.drop_table("system_audit_log", schema="observability")
    op.drop_index(
        "ix_notif_outbox_pending",
        table_name="notification_outbox",
        schema="notifications",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_table("notification_outbox", schema="notifications")
    op.drop_index("uq_users_email_lower", table_name="users", schema="identity")
    op.drop_table("users", schema="identity")
    op.drop_table("tenants", schema="identity")
    op.drop_table("platform_settings", schema="identity")
    # ### end Alembic commands ###
