"""notification_outbox

Revision ID: ff84f2df4d2f
Revises: 699ca3b82d04
Create Date: 2026-08-05 15:00:07.154293

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ff84f2df4d2f"
down_revision: str | Sequence[str] | None = "699ca3b82d04"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notification_templates",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("event_type", sa.String(length=255), nullable=False),
        sa.Column("channel", sa.String(length=50), nullable=False),
        sa.Column("subject_template", sa.Text(), nullable=True),
        sa.Column("body_template", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["ucp.tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        schema="ucp",
    )
    op.create_table(
        "notification_outbox",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_reason", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("owner_token", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
        schema="ucp",
    )
    op.create_index(
        "ix_notif_outbox_pending",
        "notification_outbox",
        ["status", "created_at"],
        unique=False,
        schema="ucp",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_table("alembic_version", schema="edi")
    op.add_column(
        "outbox", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False), schema="edi"
    )
    op.add_column(
        "outbox", sa.Column("owner_token", sa.String(length=128), nullable=True), schema="edi"
    )
    op.add_column(
        "outbox",
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        schema="edi",
    )
    op.alter_column(
        "outbox",
        "idempotency_key",
        existing_type=sa.VARCHAR(length=128),
        type_=sa.String(length=255),
        existing_nullable=False,
        schema="edi",
    )
    op.create_index(
        op.f("ix_edi_outbox_tenant_id"), "outbox", ["tenant_id"], unique=False, schema="edi"
    )
    op.alter_column(
        "api_keys",
        "key_hash",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        schema="ucp",
    )
    op.alter_column(
        "api_keys",
        "name",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=False,
        schema="ucp",
    )
    op.alter_column(
        "api_keys",
        "scopes",
        existing_type=postgresql.ARRAY(sa.TEXT()),
        type_=postgresql.ARRAY(sa.String()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::text[]"),
        schema="ucp",
    )
    op.alter_column(
        "api_keys",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
        schema="ucp",
    )
    op.drop_index(op.f("api_keys_tenant_idx"), table_name="api_keys", schema="ucp")
    op.create_index(
        op.f("ix_ucp_api_keys_tenant_id"), "api_keys", ["tenant_id"], unique=False, schema="ucp"
    )
    op.drop_constraint(
        op.f("api_keys_tenant_id_tenants_id_fk"), "api_keys", schema="ucp", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_api_keys_tenant_id_tenants",
        "api_keys",
        "tenants",
        ["tenant_id"],
        ["id"],
        source_schema="ucp",
        referent_schema="ucp",
        ondelete="CASCADE",
    )
    op.drop_index(op.f("api_tokens_tenant_idx"), table_name="api_tokens", schema="ucp")
    op.create_index(
        op.f("ix_ucp_api_tokens_tenant_id"), "api_tokens", ["tenant_id"], unique=False, schema="ucp"
    )
    op.drop_constraint(
        op.f("app_subscriptions_tenant_id_tenants_id_fk"),
        "app_subscriptions",
        schema="ucp",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("app_subscriptions_app_id_apps_id_fk"),
        "app_subscriptions",
        schema="ucp",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_app_subscriptions_app_id_apps",
        "app_subscriptions",
        "apps",
        ["app_id"],
        ["id"],
        source_schema="ucp",
        referent_schema="ucp",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_app_subscriptions_tenant_id_tenants",
        "app_subscriptions",
        "tenants",
        ["tenant_id"],
        ["id"],
        source_schema="ucp",
        referent_schema="ucp",
        ondelete="CASCADE",
    )
    op.drop_column("app_subscriptions", "updated_at", schema="ucp")
    op.drop_column("app_subscriptions", "status", schema="ucp")
    op.drop_column("app_subscriptions", "created_at", schema="ucp")
    op.drop_column("app_subscriptions", "expires_at", schema="ucp")
    op.alter_column(
        "apps",
        "name",
        existing_type=sa.TEXT(),
        type_=sa.String(length=255),
        existing_nullable=False,
        schema="ucp",
    )
    op.drop_column("apps", "created_at", schema="ucp")
    op.drop_column("apps", "description", schema="ucp")
    op.drop_index(
        op.f("notification_template_idx"), table_name="notification_templates", schema="ucp"
    )
    op.create_unique_constraint(
        "notification_template_idx",
        "notification_templates",
        ["tenant_id", "event_type", "channel"],
        schema="ucp",
    )
    op.alter_column(
        "outbox", "tenant_id", existing_type=sa.VARCHAR(length=128), nullable=False, schema="ucp"
    )
    op.alter_column(
        "outbox",
        "error_reason",
        existing_type=sa.TEXT(),
        type_=sa.String(),
        existing_nullable=True,
        schema="ucp",
    )
    op.alter_column(
        "outbox",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
        schema="ucp",
    )
    op.alter_column(
        "outbox",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
        schema="ucp",
    )
    op.create_index(
        "ix_global_outbox_pending",
        "outbox",
        ["status", "created_at"],
        unique=False,
        schema="ucp",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_constraint(
        op.f("outbox_tenant_id_tenants_id_fk"), "outbox", schema="ucp", type_="foreignkey"
    )
    op.alter_column(
        "platform_settings",
        "value",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_nullable=True,
        schema="ucp",
    )
    op.drop_constraint(
        op.f("shard_registry_tenant_id_tenants_id_fk"),
        "shard_registry",
        schema="ucp",
        type_="foreignkey",
    )
    op.create_foreign_key(
        "fk_shard_registry_tenant_id_tenants",
        "shard_registry",
        "tenants",
        ["tenant_id"],
        ["id"],
        source_schema="ucp",
        referent_schema="ucp",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_shard_registry_app_id_apps",
        "shard_registry",
        "apps",
        ["app_id"],
        ["id"],
        source_schema="ucp",
        referent_schema="ucp",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_shard_registry_shard_id_database_shards",
        "shard_registry",
        "database_shards",
        ["shard_id"],
        ["id"],
        source_schema="ucp",
        referent_schema="ucp",
        ondelete="CASCADE",
    )
    op.drop_column("shard_registry", "status", schema="ucp")
    op.drop_index(op.f("tenant_users_user_id_idx"), table_name="tenant_users", schema="ucp")
    op.drop_constraint(
        op.f("tenant_users_tenant_id_tenants_id_fk"),
        "tenant_users",
        schema="ucp",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("tenant_users_user_id_users_id_fk"), "tenant_users", schema="ucp", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_tenant_users_user_id_users",
        "tenant_users",
        "users",
        ["user_id"],
        ["id"],
        source_schema="ucp",
        referent_schema="ucp",
        ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_tenant_users_tenant_id_tenants",
        "tenant_users",
        "tenants",
        ["tenant_id"],
        ["id"],
        source_schema="ucp",
        referent_schema="ucp",
        ondelete="CASCADE",
    )
    op.drop_column("tenant_users", "metadata", schema="ucp")
    op.alter_column(
        "tenants",
        "name",
        existing_type=sa.TEXT(),
        type_=sa.String(length=255),
        existing_nullable=False,
        schema="ucp",
    )
    op.create_unique_constraint("uq_tenants_name", "tenants", ["name"], schema="ucp")
    op.alter_column(
        "users",
        "name",
        existing_type=sa.TEXT(),
        type_=sa.String(length=255),
        existing_nullable=False,
        schema="ucp",
    )
    op.create_index(
        "uq_users_email_lower",
        "users",
        [sa.literal_column("lower(email)")],
        unique=True,
        schema="ucp",
    )
    op.drop_index(op.f("webhooks_tenant_idx"), table_name="webhooks", schema="ucp")
    op.create_index(
        op.f("ix_ucp_webhooks_tenant_id"), "webhooks", ["tenant_id"], unique=False, schema="ucp"
    )
    op.drop_constraint(
        op.f("webhooks_tenant_id_tenants_id_fk"), "webhooks", schema="ucp", type_="foreignkey"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("webhooks_tenant_id_tenants_id_fk"),
        "webhooks",
        "tenants",
        ["tenant_id"],
        ["id"],
        source_schema="ucp",
        referent_schema="ucp",
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_ucp_webhooks_tenant_id"), table_name="webhooks", schema="ucp")
    op.create_index(
        op.f("webhooks_tenant_idx"), "webhooks", ["tenant_id"], unique=False, schema="ucp"
    )
    op.drop_index("uq_users_email_lower", table_name="users", schema="ucp")
    op.alter_column(
        "users",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.TEXT(),
        existing_nullable=False,
        schema="ucp",
    )
    op.drop_constraint("uq_tenants_name", "tenants", schema="ucp", type_="unique")
    op.alter_column(
        "tenants",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.TEXT(),
        existing_nullable=False,
        schema="ucp",
    )
    op.add_column(
        "tenant_users",
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True
        ),
        schema="ucp",
    )
    op.drop_constraint("fk_tenant_users_user_id_users", "tenant_users", schema="ucp", type_="foreignkey")
    op.drop_constraint("fk_tenant_users_tenant_id_tenants", "tenant_users", schema="ucp", type_="foreignkey")
    op.create_foreign_key(
        op.f("tenant_users_user_id_users_id_fk"),
        "tenant_users",
        "users",
        ["user_id"],
        ["id"],
        source_schema="ucp",
        referent_schema="ucp",
    )
    op.create_foreign_key(
        op.f("tenant_users_tenant_id_tenants_id_fk"),
        "tenant_users",
        "tenants",
        ["tenant_id"],
        ["id"],
        source_schema="ucp",
        referent_schema="ucp",
    )
    op.create_index(
        op.f("tenant_users_user_id_idx"), "tenant_users", ["user_id"], unique=False, schema="ucp"
    )
    op.add_column(
        "shard_registry",
        sa.Column(
            "status",
            sa.VARCHAR(length=50),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        schema="ucp",
    )
    op.drop_constraint("fk_shard_registry_shard_id_database_shards", "shard_registry", schema="ucp", type_="foreignkey")
    op.drop_constraint("fk_shard_registry_app_id_apps", "shard_registry", schema="ucp", type_="foreignkey")
    op.drop_constraint("fk_shard_registry_tenant_id_tenants", "shard_registry", schema="ucp", type_="foreignkey")
    op.create_foreign_key(
        op.f("shard_registry_tenant_id_tenants_id_fk"),
        "shard_registry",
        "tenants",
        ["tenant_id"],
        ["id"],
        source_schema="ucp",
        referent_schema="ucp",
    )
    op.alter_column(
        "platform_settings",
        "value",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_nullable=True,
        schema="ucp",
    )
    op.create_foreign_key(
        op.f("outbox_tenant_id_tenants_id_fk"),
        "outbox",
        "tenants",
        ["tenant_id"],
        ["id"],
        source_schema="ucp",
        referent_schema="ucp",
    )
    op.drop_index(
        "ix_global_outbox_pending",
        table_name="outbox",
        schema="ucp",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.alter_column(
        "outbox",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
        schema="ucp",
    )
    op.alter_column(
        "outbox",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
        schema="ucp",
    )
    op.alter_column(
        "outbox",
        "error_reason",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=True,
        schema="ucp",
    )
    op.alter_column(
        "outbox", "tenant_id", existing_type=sa.VARCHAR(length=128), nullable=True, schema="ucp"
    )
    op.drop_constraint(
        "notification_template_idx", "notification_templates", schema="ucp", type_="unique"
    )
    op.create_index(
        op.f("notification_template_idx"),
        "notification_templates",
        ["tenant_id", "event_type", "channel"],
        unique=True,
        schema="ucp",
    )
    op.add_column(
        "apps",
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        schema="ucp",
    )
    op.add_column(
        "apps",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        schema="ucp",
    )
    op.alter_column(
        "apps",
        "name",
        existing_type=sa.String(length=255),
        type_=sa.TEXT(),
        existing_nullable=False,
        schema="ucp",
    )
    op.add_column(
        "app_subscriptions",
        sa.Column("expires_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
        schema="ucp",
    )
    op.add_column(
        "app_subscriptions",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        schema="ucp",
    )
    op.add_column(
        "app_subscriptions",
        sa.Column(
            "status",
            sa.VARCHAR(length=50),
            server_default=sa.text("'active'::character varying"),
            autoincrement=False,
            nullable=False,
        ),
        schema="ucp",
    )
    op.add_column(
        "app_subscriptions",
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        schema="ucp",
    )
    op.drop_constraint("fk_app_subscriptions_tenant_id_tenants", "app_subscriptions", schema="ucp", type_="foreignkey")
    op.drop_constraint("fk_app_subscriptions_app_id_apps", "app_subscriptions", schema="ucp", type_="foreignkey")
    op.create_foreign_key(
        op.f("app_subscriptions_app_id_apps_id_fk"),
        "app_subscriptions",
        "apps",
        ["app_id"],
        ["id"],
        source_schema="ucp",
        referent_schema="ucp",
    )
    op.create_foreign_key(
        op.f("app_subscriptions_tenant_id_tenants_id_fk"),
        "app_subscriptions",
        "tenants",
        ["tenant_id"],
        ["id"],
        source_schema="ucp",
        referent_schema="ucp",
    )
    op.drop_index(op.f("ix_ucp_api_tokens_tenant_id"), table_name="api_tokens", schema="ucp")
    op.create_index(
        op.f("api_tokens_tenant_idx"), "api_tokens", ["tenant_id"], unique=False, schema="ucp"
    )
    op.drop_constraint("fk_api_keys_tenant_id_tenants", "api_keys", schema="ucp", type_="foreignkey")
    op.create_foreign_key(
        op.f("api_keys_tenant_id_tenants_id_fk"),
        "api_keys",
        "tenants",
        ["tenant_id"],
        ["id"],
        source_schema="ucp",
        referent_schema="ucp",
    )
    op.drop_index(op.f("ix_ucp_api_keys_tenant_id"), table_name="api_keys", schema="ucp")
    op.create_index(
        op.f("api_keys_tenant_idx"), "api_keys", ["tenant_id"], unique=False, schema="ucp"
    )
    op.alter_column(
        "api_keys",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
        schema="ucp",
    )
    op.alter_column(
        "api_keys",
        "scopes",
        existing_type=postgresql.ARRAY(sa.String()),
        type_=postgresql.ARRAY(sa.TEXT()),
        existing_nullable=False,
        existing_server_default=sa.text("'{}'::text[]"),
        schema="ucp",
    )
    op.alter_column(
        "api_keys",
        "name",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        schema="ucp",
    )
    op.alter_column(
        "api_keys",
        "key_hash",
        existing_type=sa.String(),
        type_=sa.TEXT(),
        existing_nullable=False,
        schema="ucp",
    )
    op.drop_index(op.f("ix_edi_outbox_tenant_id"), table_name="outbox", schema="edi")
    op.alter_column(
        "outbox",
        "idempotency_key",
        existing_type=sa.String(length=255),
        type_=sa.VARCHAR(length=128),
        existing_nullable=False,
        schema="edi",
    )
    op.drop_column("outbox", "lease_expires_at", schema="edi")
    op.drop_column("outbox", "owner_token", schema="edi")
    op.drop_column("outbox", "updated_at", schema="edi")
    op.create_table(
        "alembic_version",
        sa.Column("version_num", sa.VARCHAR(length=32), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("version_num", name=op.f("alembic_version_pkc")),
        schema="edi",
    )
    op.drop_index(
        "ix_notif_outbox_pending",
        table_name="notification_outbox",
        schema="ucp",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_table("notification_outbox", schema="ucp")
    op.drop_table("notification_templates", schema="ucp")
    # ### end Alembic commands ###
