# generated by datamodel-codegen:
#   filename:  event-message.json
#   timestamp: 2026-07-31T07:21:33+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

from . import edi_events, ucp_events, webhook_events


class EventMessage(BaseModel):
    idempotencyKey: str = Field(..., description='Unique key for idempotency')
    tenantId: str | None = Field(
        None, description='The tenant ID this event belongs to'
    )
    eventType: (
        ucp_events.UcpEventType
        | edi_events.EdiEventType
        | webhook_events.WebhookEventType
    )
    payload: dict[str, Any] = Field(
        ..., description='The event payload, which varies by eventType'
    )
