# generated by datamodel-codegen:
#   filename:  event-message.json
#   timestamp: 2026-07-22T17:31:45+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

from . import event_type


class EventMessage(BaseModel):
    idempotencyKey: str = Field(..., description='Unique key for idempotency')
    tenantId: str | None = Field(
        None, description='The tenant ID this event belongs to'
    )
    eventType: event_type.EventType
    payload: dict[str, Any] = Field(
        ..., description='The event payload, which varies by eventType'
    )
