# generated by datamodel-codegen:
#   filename:  event-type.json
#   timestamp: 2026-07-22T17:31:45+00:00

from __future__ import annotations

from enum import Enum


class EventType(Enum):
    tenant_provisioned = 'tenant.provisioned'
    api_key_created = 'api_key.created'
