/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTenantsIndexRouteImport } from './routes/_authenticated/tenants/index'
import { Route as AuthenticatedTenantsTenantIdRouteImport } from './routes/_authenticated/tenants/$tenantId'
import { Route as AuthenticatedTenantsTenantIdIndexRouteImport } from './routes/_authenticated/tenants/$tenantId/index'
import { Route as AuthenticatedTenantsTenantIdAppsRouteImport } from './routes/_authenticated/tenants/$tenantId/apps'
import { Route as AuthenticatedTenantsTenantIdUsersRouteImport } from './routes/_authenticated/tenants/$tenantId/users'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTenantsIndexRoute =
  AuthenticatedTenantsIndexRouteImport.update({
    id: '/tenants/',
    path: '/tenants/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsTenantIdRoute =
  AuthenticatedTenantsTenantIdRouteImport.update({
    id: '/tenants/$tenantId',
    path: '/tenants/$tenantId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTenantsTenantIdIndexRoute =
  AuthenticatedTenantsTenantIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedTenantsTenantIdRoute,
  } as any)
const AuthenticatedTenantsTenantIdAppsRoute =
  AuthenticatedTenantsTenantIdAppsRouteImport.update({
    id: '/apps',
    path: '/apps',
    getParentRoute: () => AuthenticatedTenantsTenantIdRoute,
  } as any)
const AuthenticatedTenantsTenantIdUsersRoute =
  AuthenticatedTenantsTenantIdUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => AuthenticatedTenantsTenantIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/callback': typeof CallbackRoute
  '/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdRouteWithChildren
  '/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/tenants/$tenantId/apps': typeof AuthenticatedTenantsTenantIdAppsRoute
  '/tenants/$tenantId/users': typeof AuthenticatedTenantsTenantIdUsersRoute
  '/tenants/$tenantId/': typeof AuthenticatedTenantsTenantIdIndexRoute
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/tenants': typeof AuthenticatedTenantsIndexRoute
  '/tenants/$tenantId/apps': typeof AuthenticatedTenantsTenantIdAppsRoute
  '/tenants/$tenantId/users': typeof AuthenticatedTenantsTenantIdUsersRoute
  '/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/callback': typeof CallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdRouteWithChildren
  '/_authenticated/tenants/': typeof AuthenticatedTenantsIndexRoute
  '/_authenticated/tenants/$tenantId/apps': typeof AuthenticatedTenantsTenantIdAppsRoute
  '/_authenticated/tenants/$tenantId/users': typeof AuthenticatedTenantsTenantIdUsersRoute
  '/_authenticated/tenants/$tenantId/': typeof AuthenticatedTenantsTenantIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/callback'
    | '/tenants/$tenantId'
    | '/tenants/'
    | '/tenants/$tenantId/apps'
    | '/tenants/$tenantId/users'
    | '/tenants/$tenantId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/callback'
    | '/'
    | '/tenants'
    | '/tenants/$tenantId/apps'
    | '/tenants/$tenantId/users'
    | '/tenants/$tenantId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/callback'
    | '/_authenticated/'
    | '/_authenticated/tenants/$tenantId'
    | '/_authenticated/tenants/'
    | '/_authenticated/tenants/$tenantId/apps'
    | '/_authenticated/tenants/$tenantId/users'
    | '/_authenticated/tenants/$tenantId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CallbackRoute: typeof CallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/': {
      id: '/_authenticated/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AuthenticatedTenantsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/$tenantId': {
      id: '/_authenticated/tenants/$tenantId'
      path: '/tenants/$tenantId'
      fullPath: '/tenants/$tenantId'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/$tenantId/': {
      id: '/_authenticated/tenants/$tenantId/'
      path: '/'
      fullPath: '/tenants/$tenantId/'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdIndexRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantIdRoute
    }
    '/_authenticated/tenants/$tenantId/apps': {
      id: '/_authenticated/tenants/$tenantId/apps'
      path: '/apps'
      fullPath: '/tenants/$tenantId/apps'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdAppsRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantIdRoute
    }
    '/_authenticated/tenants/$tenantId/users': {
      id: '/_authenticated/tenants/$tenantId/users'
      path: '/users'
      fullPath: '/tenants/$tenantId/users'
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdUsersRouteImport
      parentRoute: typeof AuthenticatedTenantsTenantIdRoute
    }
  }
}

interface AuthenticatedTenantsTenantIdRouteChildren {
  AuthenticatedTenantsTenantIdAppsRoute: typeof AuthenticatedTenantsTenantIdAppsRoute
  AuthenticatedTenantsTenantIdUsersRoute: typeof AuthenticatedTenantsTenantIdUsersRoute
  AuthenticatedTenantsTenantIdIndexRoute: typeof AuthenticatedTenantsTenantIdIndexRoute
}

const AuthenticatedTenantsTenantIdRouteChildren: AuthenticatedTenantsTenantIdRouteChildren =
  {
    AuthenticatedTenantsTenantIdAppsRoute:
      AuthenticatedTenantsTenantIdAppsRoute,
    AuthenticatedTenantsTenantIdUsersRoute:
      AuthenticatedTenantsTenantIdUsersRoute,
    AuthenticatedTenantsTenantIdIndexRoute:
      AuthenticatedTenantsTenantIdIndexRoute,
  }

const AuthenticatedTenantsTenantIdRouteWithChildren =
  AuthenticatedTenantsTenantIdRoute._addFileChildren(
    AuthenticatedTenantsTenantIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedTenantsTenantIdRoute: typeof AuthenticatedTenantsTenantIdRouteWithChildren
  AuthenticatedTenantsIndexRoute: typeof AuthenticatedTenantsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTenantsTenantIdRoute:
    AuthenticatedTenantsTenantIdRouteWithChildren,
  AuthenticatedTenantsIndexRoute: AuthenticatedTenantsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
