/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedTenantsRouteImport } from './routes/_authenticated/tenants'
import { Route as AuthenticatedTenantsIdKeysRouteImport } from './routes/_authenticated/tenants.$id.keys'
import { Route as AuthenticatedTenantsIdWebhooksRouteImport } from './routes/_authenticated/tenants.$id.webhooks'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTenantsRoute = AuthenticatedTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTenantsIdKeysRoute =
  AuthenticatedTenantsIdKeysRouteImport.update({
    id: '/$id/keys',
    path: '/$id/keys',
    getParentRoute: () => AuthenticatedTenantsRoute,
  } as any)
const AuthenticatedTenantsIdWebhooksRoute =
  AuthenticatedTenantsIdWebhooksRouteImport.update({
    id: '/$id/webhooks',
    path: '/$id/webhooks',
    getParentRoute: () => AuthenticatedTenantsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/tenants/$id/keys': typeof AuthenticatedTenantsIdKeysRoute
  '/tenants/$id/webhooks': typeof AuthenticatedTenantsIdWebhooksRoute
}
export interface FileRoutesByTo {
  '/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/tenants/$id/keys': typeof AuthenticatedTenantsIdKeysRoute
  '/tenants/$id/webhooks': typeof AuthenticatedTenantsIdWebhooksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_authenticated/tenants': typeof AuthenticatedTenantsRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/tenants/$id/keys': typeof AuthenticatedTenantsIdKeysRoute
  '/_authenticated/tenants/$id/webhooks': typeof AuthenticatedTenantsIdWebhooksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/tenants' | '/tenants/$id/keys' | '/tenants/$id/webhooks'
  fileRoutesByTo: FileRoutesByTo
  to: '/tenants' | '/' | '/tenants/$id/keys' | '/tenants/$id/webhooks'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/tenants'
    | '/_authenticated/'
    | '/_authenticated/tenants/$id/keys'
    | '/_authenticated/tenants/$id/webhooks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants': {
      id: '/_authenticated/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof AuthenticatedTenantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tenants/$id/keys': {
      id: '/_authenticated/tenants/$id/keys'
      path: '/$id/keys'
      fullPath: '/tenants/$id/keys'
      preLoaderRoute: typeof AuthenticatedTenantsIdKeysRouteImport
      parentRoute: typeof AuthenticatedTenantsRoute
    }
    '/_authenticated/tenants/$id/webhooks': {
      id: '/_authenticated/tenants/$id/webhooks'
      path: '/$id/webhooks'
      fullPath: '/tenants/$id/webhooks'
      preLoaderRoute: typeof AuthenticatedTenantsIdWebhooksRouteImport
      parentRoute: typeof AuthenticatedTenantsRoute
    }
  }
}

interface AuthenticatedTenantsRouteChildren {
  AuthenticatedTenantsIdKeysRoute: typeof AuthenticatedTenantsIdKeysRoute
  AuthenticatedTenantsIdWebhooksRoute: typeof AuthenticatedTenantsIdWebhooksRoute
}

const AuthenticatedTenantsRouteChildren: AuthenticatedTenantsRouteChildren = {
  AuthenticatedTenantsIdKeysRoute: AuthenticatedTenantsIdKeysRoute,
  AuthenticatedTenantsIdWebhooksRoute: AuthenticatedTenantsIdWebhooksRoute,
}

const AuthenticatedTenantsRouteWithChildren =
  AuthenticatedTenantsRoute._addFileChildren(AuthenticatedTenantsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedTenantsRoute: typeof AuthenticatedTenantsRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedTenantsRoute: AuthenticatedTenantsRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
