from collections.abc import Sequence
from typing import Protocol

from edi.domain.models.as2 import AS2PartnerDomainModel


class AS2TradingPartnerRepositoryPort(Protocol):
    async def save(self, aggregate: AS2PartnerDomainModel) -> None: ...
    async def get_as2_partner(
        self, tenant_id: str, partner_id: str
    ) -> AS2PartnerDomainModel | None: ...
    async def delete(self, aggregate: AS2PartnerDomainModel) -> None: ...
    async def get_as2_partners_by_ids(self, tenant_id: str, ids: list[str]) -> dict[str, str]: ...
    async def list_as2_partners(self, tenant_id: str) -> Sequence[AS2PartnerDomainModel]: ...
    async def is_vault_ref_in_use(self, vault_ref: str) -> bool: ...
