from typing import Protocol

from edi.domain.models.as2 import AS2PartnerDomainModel, AS2PartnershipDomainModel


class AS2PartnershipRepositoryPort(Protocol):
    async def save(self, aggregate: AS2PartnershipDomainModel) -> None: ...
    async def delete(self, aggregate: AS2PartnershipDomainModel) -> None: ...
    async def get_as2_partnership(
        self, tenant_id: str, partnership_id: str
    ) -> AS2PartnershipDomainModel | None: ...
    async def list_as2_partnerships(self, tenant_id: str) -> list[AS2PartnershipDomainModel]: ...
    async def get_partnership_by_as2_ids(
        self, as2_from: str, as2_to: str
    ) -> tuple[AS2PartnershipDomainModel, AS2PartnerDomainModel, AS2PartnerDomainModel] | None: ...
