from typing import Protocol

from edi.domain.models.outbound_routes import OutboundRouteDomainModel


class OutboundRouteRepositoryPort(Protocol):
    async def save(self, aggregate: OutboundRouteDomainModel) -> None: ...
    async def delete(self, aggregate: OutboundRouteDomainModel) -> None: ...
    async def get_outbound_route(
        self, tenant_id: str, route_id: str
    ) -> OutboundRouteDomainModel | None: ...
    async def get_outbound_route_by_trading_partner_id(
        self, tenant_id: str, trading_partner_id: str
    ) -> OutboundRouteDomainModel | None: ...
    async def list_outbound_routes(self, tenant_id: str) -> list[OutboundRouteDomainModel]: ...
