from collections.abc import Sequence
from typing import Protocol

from edi.domain.models.sftp import SFTPPartnerDomainModel


class SFTPPartnerRepositoryPort(Protocol):
    async def save(self, aggregate: SFTPPartnerDomainModel) -> None: ...
    async def delete(self, aggregate: SFTPPartnerDomainModel) -> None: ...
    async def get_sftp_partner(
        self, tenant_id: str, partner_id: str
    ) -> SFTPPartnerDomainModel | None: ...
    async def list_sftp_partners(self, tenant_id: str) -> Sequence[SFTPPartnerDomainModel]: ...
    async def get_sftp_partners_by_ids(self, tenant_id: str, ids: list[str]) -> dict[str, str]: ...
