version: '3.8'

services:
  ucp_engine:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: ../../.env
    ports:
      - "3001:3001"
      - "3002:3002"
    depends_on:
      postgres_global:
        condition: service_healthy
      localstack:
        condition: service_started
