/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as TenantRouteImport } from './routes/tenant'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as PlatformDashboardRouteImport } from './routes/platform/dashboard'
import { Route as PlatformUsersRouteImport } from './routes/platform/users'
import { Route as TenantDashboardRouteImport } from './routes/tenant/dashboard'
import { Route as TenantEdi_setupRouteImport } from './routes/tenant/edi_setup'
import { Route as TenantEdi_toolRouteImport } from './routes/tenant/edi_tool'
import { Route as TenantPartnersRouteImport } from './routes/tenant/partners'
import { Route as TenantUsersRouteImport } from './routes/tenant/users'
import { Route as TenantWebhooksRouteImport } from './routes/tenant/webhooks'
import { Route as TenantTransactionsIndexRouteImport } from './routes/tenant/transactions/index'
import { Route as TenantTransactionsTraceIdRouteImport } from './routes/tenant/transactions/$traceId'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRoute = TenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const PlatformDashboardRoute = PlatformDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PlatformRoute,
} as any)
const PlatformUsersRoute = PlatformUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PlatformRoute,
} as any)
const TenantDashboardRoute = TenantDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => TenantRoute,
} as any)
const TenantEdi_setupRoute = TenantEdi_setupRouteImport.update({
  id: '/edi_setup',
  path: '/edi_setup',
  getParentRoute: () => TenantRoute,
} as any)
const TenantEdi_toolRoute = TenantEdi_toolRouteImport.update({
  id: '/edi_tool',
  path: '/edi_tool',
  getParentRoute: () => TenantRoute,
} as any)
const TenantPartnersRoute = TenantPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => TenantRoute,
} as any)
const TenantUsersRoute = TenantUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => TenantRoute,
} as any)
const TenantWebhooksRoute = TenantWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => TenantRoute,
} as any)
const TenantTransactionsIndexRoute = TenantTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => TenantRoute,
} as any)
const TenantTransactionsTraceIdRoute =
  TenantTransactionsTraceIdRouteImport.update({
    id: '/transactions/$traceId',
    path: '/transactions/$traceId',
    getParentRoute: () => TenantRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/platform': typeof PlatformRouteWithChildren
  '/tenant': typeof TenantRouteWithChildren
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/users': typeof PlatformUsersRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/edi_setup': typeof TenantEdi_setupRoute
  '/tenant/edi_tool': typeof TenantEdi_toolRoute
  '/tenant/partners': typeof TenantPartnersRoute
  '/tenant/users': typeof TenantUsersRoute
  '/tenant/webhooks': typeof TenantWebhooksRoute
  '/tenant/transactions/$traceId': typeof TenantTransactionsTraceIdRoute
  '/tenant/transactions/': typeof TenantTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/platform': typeof PlatformRouteWithChildren
  '/tenant': typeof TenantRouteWithChildren
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/users': typeof PlatformUsersRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/edi_setup': typeof TenantEdi_setupRoute
  '/tenant/edi_tool': typeof TenantEdi_toolRoute
  '/tenant/partners': typeof TenantPartnersRoute
  '/tenant/users': typeof TenantUsersRoute
  '/tenant/webhooks': typeof TenantWebhooksRoute
  '/': typeof MarketingIndexRoute
  '/tenant/transactions/$traceId': typeof TenantTransactionsTraceIdRoute
  '/tenant/transactions': typeof TenantTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/platform': typeof PlatformRouteWithChildren
  '/tenant': typeof TenantRouteWithChildren
  '/platform/dashboard': typeof PlatformDashboardRoute
  '/platform/users': typeof PlatformUsersRoute
  '/tenant/dashboard': typeof TenantDashboardRoute
  '/tenant/edi_setup': typeof TenantEdi_setupRoute
  '/tenant/edi_tool': typeof TenantEdi_toolRoute
  '/tenant/partners': typeof TenantPartnersRoute
  '/tenant/users': typeof TenantUsersRoute
  '/tenant/webhooks': typeof TenantWebhooksRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/tenant/transactions/$traceId': typeof TenantTransactionsTraceIdRoute
  '/tenant/transactions/': typeof TenantTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/platform'
    | '/tenant'
    | '/platform/dashboard'
    | '/platform/users'
    | '/tenant/dashboard'
    | '/tenant/edi_setup'
    | '/tenant/edi_tool'
    | '/tenant/partners'
    | '/tenant/users'
    | '/tenant/webhooks'
    | '/tenant/transactions/$traceId'
    | '/tenant/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/platform'
    | '/tenant'
    | '/platform/dashboard'
    | '/platform/users'
    | '/tenant/dashboard'
    | '/tenant/edi_setup'
    | '/tenant/edi_tool'
    | '/tenant/partners'
    | '/tenant/users'
    | '/tenant/webhooks'
    | '/'
    | '/tenant/transactions/$traceId'
    | '/tenant/transactions'
  id:
    | '__root__'
    | '/_marketing'
    | '/platform'
    | '/tenant'
    | '/platform/dashboard'
    | '/platform/users'
    | '/tenant/dashboard'
    | '/tenant/edi_setup'
    | '/tenant/edi_tool'
    | '/tenant/partners'
    | '/tenant/users'
    | '/tenant/webhooks'
    | '/_marketing/'
    | '/tenant/transactions/$traceId'
    | '/tenant/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  PlatformRoute: typeof PlatformRouteWithChildren
  TenantRoute: typeof TenantRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant': {
      id: '/tenant'
      path: '/tenant'
      fullPath: '/tenant'
      preLoaderRoute: typeof TenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/platform/dashboard': {
      id: '/platform/dashboard'
      path: '/dashboard'
      fullPath: '/platform/dashboard'
      preLoaderRoute: typeof PlatformDashboardRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/platform/users': {
      id: '/platform/users'
      path: '/users'
      fullPath: '/platform/users'
      preLoaderRoute: typeof PlatformUsersRouteImport
      parentRoute: typeof PlatformRoute
    }
    '/tenant/dashboard': {
      id: '/tenant/dashboard'
      path: '/dashboard'
      fullPath: '/tenant/dashboard'
      preLoaderRoute: typeof TenantDashboardRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/edi_setup': {
      id: '/tenant/edi_setup'
      path: '/edi_setup'
      fullPath: '/tenant/edi_setup'
      preLoaderRoute: typeof TenantEdi_setupRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/edi_tool': {
      id: '/tenant/edi_tool'
      path: '/edi_tool'
      fullPath: '/tenant/edi_tool'
      preLoaderRoute: typeof TenantEdi_toolRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/partners': {
      id: '/tenant/partners'
      path: '/partners'
      fullPath: '/tenant/partners'
      preLoaderRoute: typeof TenantPartnersRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/users': {
      id: '/tenant/users'
      path: '/users'
      fullPath: '/tenant/users'
      preLoaderRoute: typeof TenantUsersRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/webhooks': {
      id: '/tenant/webhooks'
      path: '/webhooks'
      fullPath: '/tenant/webhooks'
      preLoaderRoute: typeof TenantWebhooksRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/transactions/': {
      id: '/tenant/transactions/'
      path: '/transactions'
      fullPath: '/tenant/transactions/'
      preLoaderRoute: typeof TenantTransactionsIndexRouteImport
      parentRoute: typeof TenantRoute
    }
    '/tenant/transactions/$traceId': {
      id: '/tenant/transactions/$traceId'
      path: '/transactions/$traceId'
      fullPath: '/tenant/transactions/$traceId'
      preLoaderRoute: typeof TenantTransactionsTraceIdRouteImport
      parentRoute: typeof TenantRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface PlatformRouteChildren {
  PlatformDashboardRoute: typeof PlatformDashboardRoute
  PlatformUsersRoute: typeof PlatformUsersRoute
}

const PlatformRouteChildren: PlatformRouteChildren = {
  PlatformDashboardRoute: PlatformDashboardRoute,
  PlatformUsersRoute: PlatformUsersRoute,
}

const PlatformRouteWithChildren = PlatformRoute._addFileChildren(
  PlatformRouteChildren,
)

interface TenantRouteChildren {
  TenantDashboardRoute: typeof TenantDashboardRoute
  TenantEdi_setupRoute: typeof TenantEdi_setupRoute
  TenantEdi_toolRoute: typeof TenantEdi_toolRoute
  TenantPartnersRoute: typeof TenantPartnersRoute
  TenantUsersRoute: typeof TenantUsersRoute
  TenantWebhooksRoute: typeof TenantWebhooksRoute
  TenantTransactionsTraceIdRoute: typeof TenantTransactionsTraceIdRoute
  TenantTransactionsIndexRoute: typeof TenantTransactionsIndexRoute
}

const TenantRouteChildren: TenantRouteChildren = {
  TenantDashboardRoute: TenantDashboardRoute,
  TenantEdi_setupRoute: TenantEdi_setupRoute,
  TenantEdi_toolRoute: TenantEdi_toolRoute,
  TenantPartnersRoute: TenantPartnersRoute,
  TenantUsersRoute: TenantUsersRoute,
  TenantWebhooksRoute: TenantWebhooksRoute,
  TenantTransactionsTraceIdRoute: TenantTransactionsTraceIdRoute,
  TenantTransactionsIndexRoute: TenantTransactionsIndexRoute,
}

const TenantRouteWithChildren =
  TenantRoute._addFileChildren(TenantRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  PlatformRoute: PlatformRouteWithChildren,
  TenantRoute: TenantRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
