# include:
# - libs/identity/docker/docker-compose.yml
services:

  edi_postgres_shard:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: edi
      POSTGRES_PASSWORD: edi_password
      POSTGRES_DB: edi_shard
    command:
    - postgres
    - -c
    - wal_level=logical
    ports:
    - 5433:5432
    volumes:
    - edi_postgres_shard_data:/var/lib/postgresql/data
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U edi -d edi_shard
      interval: 5s
      timeout: 5s
      retries: 5



volumes:
  edi_postgres_shard_data: null
  postgres_enterprise_1_data: null
