version: '3.9'
# include:
# - libs/identity/docker/docker-compose.yml
services:

  edi_postgres_shard:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: edi
      POSTGRES_PASSWORD: edi_password
      POSTGRES_DB: edi_shard_1
    command:
    - postgres
    - -c
    - wal_level=logical
    ports:
    - 5433:5432
    volumes:
    - edi_postgres_shard_data:/var/lib/postgresql/data
    healthcheck:
      test:
      - CMD-SHELL
      - pg_isready -U edi -d edi_shard_1
      interval: 5s
      timeout: 5s
      retries: 5



  debezium_shard:
    image: quay.io/debezium/server:3.6.0.Final
    environment:
    - DEBEZIUM_SOURCE_DATABASE_HOSTNAME=edi_postgres_shard
    - DEBEZIUM_SOURCE_DATABASE_PORT=5432
    - DEBEZIUM_SOURCE_DATABASE_USER=edi
    - DEBEZIUM_SOURCE_DATABASE_PASSWORD=edi_password
    - DEBEZIUM_SOURCE_DATABASE_DBNAME=edi_shard_1
    extra_hosts:
    - host.docker.internal:host-gateway
    volumes:
    - ./docker/debezium/application.properties:/debezium/config/application.properties
    - debezium_data:/debezium/data
    depends_on:
      edi_postgres_shard:
        condition: service_healthy
volumes:
  edi_postgres_shard_data: null
  postgres_enterprise_1_data: null
  debezium_data: null
