/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as AuthenticatedRouteImport } from './routes/_authenticated';
import { Route as AuthenticatedEdiRouteImport } from './routes/_authenticated/edi';
import { Route as AuthenticatedEdiHeadersRouteImport } from './routes/_authenticated/edi/headers';
import { Route as AuthenticatedEdiPartnersRouteImport } from './routes/_authenticated/edi/partners';
import { Route as AuthenticatedEdiRoutesRouteImport } from './routes/_authenticated/edi/routes';
import { Route as AuthenticatedEdiToolsRouteImport } from './routes/_authenticated/edi/tools';
import { Route as AuthenticatedEdiWebhooksRouteImport } from './routes/_authenticated/edi/webhooks';
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index';
import { Route as AuthenticatedTenantsTenantIdRouteImport } from './routes/_authenticated/tenants/$tenantId';
import { Route as AuthenticatedTenantsTenantIdApiTokensRouteImport } from './routes/_authenticated/tenants/$tenantId/api-tokens';
import { Route as AuthenticatedTenantsTenantIdAppsRouteImport } from './routes/_authenticated/tenants/$tenantId/apps';
import { Route as AuthenticatedTenantsTenantIdIndexRouteImport } from './routes/_authenticated/tenants/$tenantId/index';
import { Route as AuthenticatedTenantsTenantIdUsersRouteImport } from './routes/_authenticated/tenants/$tenantId/users';
import { Route as AuthenticatedTenantsTenantIdWebhooksRouteImport } from './routes/_authenticated/tenants/$tenantId/webhooks';
import { Route as AuthenticatedTenantsIndexRouteImport } from './routes/_authenticated/tenants/index';
import { Route as CallbackRouteImport } from './routes/callback';

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any);
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any);
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedEdiRoute = AuthenticatedEdiRouteImport.update({
  id: '/edi',
  path: '/edi',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedEdiHeadersRoute = AuthenticatedEdiHeadersRouteImport.update({
  id: '/headers',
  path: '/headers',
  getParentRoute: () => AuthenticatedEdiRoute,
} as any);
const AuthenticatedEdiPartnersRoute = AuthenticatedEdiPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthenticatedEdiRoute,
} as any);
const AuthenticatedEdiRoutesRoute = AuthenticatedEdiRoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => AuthenticatedEdiRoute,
} as any);
const AuthenticatedEdiToolsRoute = AuthenticatedEdiToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AuthenticatedEdiRoute,
} as any);
const AuthenticatedEdiWebhooksRoute = AuthenticatedEdiWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AuthenticatedEdiRoute,
} as any);
const AuthenticatedTenantsIndexRoute = AuthenticatedTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedTenantsTenantIdRoute = AuthenticatedTenantsTenantIdRouteImport.update({
  id: '/tenants/$tenantId',
  path: '/tenants/$tenantId',
  getParentRoute: () => AuthenticatedRoute,
} as any);
const AuthenticatedTenantsTenantIdIndexRoute = AuthenticatedTenantsTenantIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedTenantsTenantIdRoute,
} as any);
const AuthenticatedTenantsTenantIdApiTokensRoute =
  AuthenticatedTenantsTenantIdApiTokensRouteImport.update({
    id: '/api-tokens',
    path: '/api-tokens',
    getParentRoute: () => AuthenticatedTenantsTenantIdRoute,
  } as any);
const AuthenticatedTenantsTenantIdAppsRoute = AuthenticatedTenantsTenantIdAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedTenantsTenantIdRoute,
} as any);
const AuthenticatedTenantsTenantIdUsersRoute = AuthenticatedTenantsTenantIdUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedTenantsTenantIdRoute,
} as any);
const AuthenticatedTenantsTenantIdWebhooksRoute =
  AuthenticatedTenantsTenantIdWebhooksRouteImport.update({
    id: '/webhooks',
    path: '/webhooks',
    getParentRoute: () => AuthenticatedTenantsTenantIdRoute,
  } as any);

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute;
  '/callback': typeof CallbackRoute;
  '/edi': typeof AuthenticatedEdiRouteWithChildren;
  '/edi/headers': typeof AuthenticatedEdiHeadersRoute;
  '/edi/partners': typeof AuthenticatedEdiPartnersRoute;
  '/edi/routes': typeof AuthenticatedEdiRoutesRoute;
  '/edi/tools': typeof AuthenticatedEdiToolsRoute;
  '/edi/webhooks': typeof AuthenticatedEdiWebhooksRoute;
  '/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdRouteWithChildren;
  '/tenants/': typeof AuthenticatedTenantsIndexRoute;
  '/tenants/$tenantId/api-tokens': typeof AuthenticatedTenantsTenantIdApiTokensRoute;
  '/tenants/$tenantId/apps': typeof AuthenticatedTenantsTenantIdAppsRoute;
  '/tenants/$tenantId/users': typeof AuthenticatedTenantsTenantIdUsersRoute;
  '/tenants/$tenantId/webhooks': typeof AuthenticatedTenantsTenantIdWebhooksRoute;
  '/tenants/$tenantId/': typeof AuthenticatedTenantsTenantIdIndexRoute;
}
export interface FileRoutesByTo {
  '/callback': typeof CallbackRoute;
  '/edi': typeof AuthenticatedEdiRouteWithChildren;
  '/': typeof AuthenticatedIndexRoute;
  '/edi/headers': typeof AuthenticatedEdiHeadersRoute;
  '/edi/partners': typeof AuthenticatedEdiPartnersRoute;
  '/edi/routes': typeof AuthenticatedEdiRoutesRoute;
  '/edi/tools': typeof AuthenticatedEdiToolsRoute;
  '/edi/webhooks': typeof AuthenticatedEdiWebhooksRoute;
  '/tenants': typeof AuthenticatedTenantsIndexRoute;
  '/tenants/$tenantId/api-tokens': typeof AuthenticatedTenantsTenantIdApiTokensRoute;
  '/tenants/$tenantId/apps': typeof AuthenticatedTenantsTenantIdAppsRoute;
  '/tenants/$tenantId/users': typeof AuthenticatedTenantsTenantIdUsersRoute;
  '/tenants/$tenantId/webhooks': typeof AuthenticatedTenantsTenantIdWebhooksRoute;
  '/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/_authenticated': typeof AuthenticatedRouteWithChildren;
  '/callback': typeof CallbackRoute;
  '/_authenticated/edi': typeof AuthenticatedEdiRouteWithChildren;
  '/_authenticated/': typeof AuthenticatedIndexRoute;
  '/_authenticated/edi/headers': typeof AuthenticatedEdiHeadersRoute;
  '/_authenticated/edi/partners': typeof AuthenticatedEdiPartnersRoute;
  '/_authenticated/edi/routes': typeof AuthenticatedEdiRoutesRoute;
  '/_authenticated/edi/tools': typeof AuthenticatedEdiToolsRoute;
  '/_authenticated/edi/webhooks': typeof AuthenticatedEdiWebhooksRoute;
  '/_authenticated/tenants/$tenantId': typeof AuthenticatedTenantsTenantIdRouteWithChildren;
  '/_authenticated/tenants/': typeof AuthenticatedTenantsIndexRoute;
  '/_authenticated/tenants/$tenantId/api-tokens': typeof AuthenticatedTenantsTenantIdApiTokensRoute;
  '/_authenticated/tenants/$tenantId/apps': typeof AuthenticatedTenantsTenantIdAppsRoute;
  '/_authenticated/tenants/$tenantId/users': typeof AuthenticatedTenantsTenantIdUsersRoute;
  '/_authenticated/tenants/$tenantId/webhooks': typeof AuthenticatedTenantsTenantIdWebhooksRoute;
  '/_authenticated/tenants/$tenantId/': typeof AuthenticatedTenantsTenantIdIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/callback'
    | '/edi'
    | '/edi/headers'
    | '/edi/partners'
    | '/edi/routes'
    | '/edi/tools'
    | '/edi/webhooks'
    | '/tenants/$tenantId'
    | '/tenants/'
    | '/tenants/$tenantId/api-tokens'
    | '/tenants/$tenantId/apps'
    | '/tenants/$tenantId/users'
    | '/tenants/$tenantId/webhooks'
    | '/tenants/$tenantId/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/callback'
    | '/edi'
    | '/'
    | '/edi/headers'
    | '/edi/partners'
    | '/edi/routes'
    | '/edi/tools'
    | '/edi/webhooks'
    | '/tenants'
    | '/tenants/$tenantId/api-tokens'
    | '/tenants/$tenantId/apps'
    | '/tenants/$tenantId/users'
    | '/tenants/$tenantId/webhooks'
    | '/tenants/$tenantId';
  id:
    | '__root__'
    | '/_authenticated'
    | '/callback'
    | '/_authenticated/edi'
    | '/_authenticated/'
    | '/_authenticated/edi/headers'
    | '/_authenticated/edi/partners'
    | '/_authenticated/edi/routes'
    | '/_authenticated/edi/tools'
    | '/_authenticated/edi/webhooks'
    | '/_authenticated/tenants/$tenantId'
    | '/_authenticated/tenants/'
    | '/_authenticated/tenants/$tenantId/api-tokens'
    | '/_authenticated/tenants/$tenantId/apps'
    | '/_authenticated/tenants/$tenantId/users'
    | '/_authenticated/tenants/$tenantId/webhooks'
    | '/_authenticated/tenants/$tenantId/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren;
  CallbackRoute: typeof CallbackRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated';
      path: '';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/callback': {
      id: '/callback';
      path: '/callback';
      fullPath: '/callback';
      preLoaderRoute: typeof CallbackRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/_authenticated/': {
      id: '/_authenticated/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof AuthenticatedIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/edi': {
      id: '/_authenticated/edi';
      path: '/edi';
      fullPath: '/edi';
      preLoaderRoute: typeof AuthenticatedEdiRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/edi/headers': {
      id: '/_authenticated/edi/headers';
      path: '/headers';
      fullPath: '/edi/headers';
      preLoaderRoute: typeof AuthenticatedEdiHeadersRouteImport;
      parentRoute: typeof AuthenticatedEdiRoute;
    };
    '/_authenticated/edi/partners': {
      id: '/_authenticated/edi/partners';
      path: '/partners';
      fullPath: '/edi/partners';
      preLoaderRoute: typeof AuthenticatedEdiPartnersRouteImport;
      parentRoute: typeof AuthenticatedEdiRoute;
    };
    '/_authenticated/edi/routes': {
      id: '/_authenticated/edi/routes';
      path: '/routes';
      fullPath: '/edi/routes';
      preLoaderRoute: typeof AuthenticatedEdiRoutesRouteImport;
      parentRoute: typeof AuthenticatedEdiRoute;
    };
    '/_authenticated/edi/tools': {
      id: '/_authenticated/edi/tools';
      path: '/tools';
      fullPath: '/edi/tools';
      preLoaderRoute: typeof AuthenticatedEdiToolsRouteImport;
      parentRoute: typeof AuthenticatedEdiRoute;
    };
    '/_authenticated/edi/webhooks': {
      id: '/_authenticated/edi/webhooks';
      path: '/webhooks';
      fullPath: '/edi/webhooks';
      preLoaderRoute: typeof AuthenticatedEdiWebhooksRouteImport;
      parentRoute: typeof AuthenticatedEdiRoute;
    };
    '/_authenticated/tenants/': {
      id: '/_authenticated/tenants/';
      path: '/tenants';
      fullPath: '/tenants/';
      preLoaderRoute: typeof AuthenticatedTenantsIndexRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/tenants/$tenantId': {
      id: '/_authenticated/tenants/$tenantId';
      path: '/tenants/$tenantId';
      fullPath: '/tenants/$tenantId';
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdRouteImport;
      parentRoute: typeof AuthenticatedRoute;
    };
    '/_authenticated/tenants/$tenantId/': {
      id: '/_authenticated/tenants/$tenantId/';
      path: '/';
      fullPath: '/tenants/$tenantId/';
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdIndexRouteImport;
      parentRoute: typeof AuthenticatedTenantsTenantIdRoute;
    };
    '/_authenticated/tenants/$tenantId/api-tokens': {
      id: '/_authenticated/tenants/$tenantId/api-tokens';
      path: '/api-tokens';
      fullPath: '/tenants/$tenantId/api-tokens';
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdApiTokensRouteImport;
      parentRoute: typeof AuthenticatedTenantsTenantIdRoute;
    };
    '/_authenticated/tenants/$tenantId/apps': {
      id: '/_authenticated/tenants/$tenantId/apps';
      path: '/apps';
      fullPath: '/tenants/$tenantId/apps';
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdAppsRouteImport;
      parentRoute: typeof AuthenticatedTenantsTenantIdRoute;
    };
    '/_authenticated/tenants/$tenantId/users': {
      id: '/_authenticated/tenants/$tenantId/users';
      path: '/users';
      fullPath: '/tenants/$tenantId/users';
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdUsersRouteImport;
      parentRoute: typeof AuthenticatedTenantsTenantIdRoute;
    };
    '/_authenticated/tenants/$tenantId/webhooks': {
      id: '/_authenticated/tenants/$tenantId/webhooks';
      path: '/webhooks';
      fullPath: '/tenants/$tenantId/webhooks';
      preLoaderRoute: typeof AuthenticatedTenantsTenantIdWebhooksRouteImport;
      parentRoute: typeof AuthenticatedTenantsTenantIdRoute;
    };
  }
}

interface AuthenticatedEdiRouteChildren {
  AuthenticatedEdiHeadersRoute: typeof AuthenticatedEdiHeadersRoute;
  AuthenticatedEdiPartnersRoute: typeof AuthenticatedEdiPartnersRoute;
  AuthenticatedEdiRoutesRoute: typeof AuthenticatedEdiRoutesRoute;
  AuthenticatedEdiToolsRoute: typeof AuthenticatedEdiToolsRoute;
  AuthenticatedEdiWebhooksRoute: typeof AuthenticatedEdiWebhooksRoute;
}

const AuthenticatedEdiRouteChildren: AuthenticatedEdiRouteChildren = {
  AuthenticatedEdiHeadersRoute: AuthenticatedEdiHeadersRoute,
  AuthenticatedEdiPartnersRoute: AuthenticatedEdiPartnersRoute,
  AuthenticatedEdiRoutesRoute: AuthenticatedEdiRoutesRoute,
  AuthenticatedEdiToolsRoute: AuthenticatedEdiToolsRoute,
  AuthenticatedEdiWebhooksRoute: AuthenticatedEdiWebhooksRoute,
};

const AuthenticatedEdiRouteWithChildren = AuthenticatedEdiRoute._addFileChildren(
  AuthenticatedEdiRouteChildren,
);

interface AuthenticatedTenantsTenantIdRouteChildren {
  AuthenticatedTenantsTenantIdApiTokensRoute: typeof AuthenticatedTenantsTenantIdApiTokensRoute;
  AuthenticatedTenantsTenantIdAppsRoute: typeof AuthenticatedTenantsTenantIdAppsRoute;
  AuthenticatedTenantsTenantIdUsersRoute: typeof AuthenticatedTenantsTenantIdUsersRoute;
  AuthenticatedTenantsTenantIdWebhooksRoute: typeof AuthenticatedTenantsTenantIdWebhooksRoute;
  AuthenticatedTenantsTenantIdIndexRoute: typeof AuthenticatedTenantsTenantIdIndexRoute;
}

const AuthenticatedTenantsTenantIdRouteChildren: AuthenticatedTenantsTenantIdRouteChildren = {
  AuthenticatedTenantsTenantIdApiTokensRoute: AuthenticatedTenantsTenantIdApiTokensRoute,
  AuthenticatedTenantsTenantIdAppsRoute: AuthenticatedTenantsTenantIdAppsRoute,
  AuthenticatedTenantsTenantIdUsersRoute: AuthenticatedTenantsTenantIdUsersRoute,
  AuthenticatedTenantsTenantIdWebhooksRoute: AuthenticatedTenantsTenantIdWebhooksRoute,
  AuthenticatedTenantsTenantIdIndexRoute: AuthenticatedTenantsTenantIdIndexRoute,
};

const AuthenticatedTenantsTenantIdRouteWithChildren =
  AuthenticatedTenantsTenantIdRoute._addFileChildren(AuthenticatedTenantsTenantIdRouteChildren);

interface AuthenticatedRouteChildren {
  AuthenticatedEdiRoute: typeof AuthenticatedEdiRouteWithChildren;
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute;
  AuthenticatedTenantsTenantIdRoute: typeof AuthenticatedTenantsTenantIdRouteWithChildren;
  AuthenticatedTenantsIndexRoute: typeof AuthenticatedTenantsIndexRoute;
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEdiRoute: AuthenticatedEdiRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedTenantsTenantIdRoute: AuthenticatedTenantsTenantIdRouteWithChildren,
  AuthenticatedTenantsIndexRoute: AuthenticatedTenantsIndexRoute,
};

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CallbackRoute: CallbackRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
