import base64
import json
import os
import shutil
import subprocess
import sys
import time
import urllib.error
import urllib.request
import uuid
from pathlib import Path

import structlog

DOCKER_BIN = shutil.which("docker")
PULUMI_BIN = shutil.which("pulumi")

if not DOCKER_BIN:
    raise RuntimeError("docker binary not found in PATH")
if not PULUMI_BIN:
    raise RuntimeError("pulumi binary not found in PATH")

logger = structlog.get_logger(__name__)


def wait_for_file(file_path: Path, max_wait_ms: int = 60000) -> None:
    """Block until file_path exists or max_wait_ms elapses."""
    start_time = time.time()
    logger.info("Waiting for file to be generated by Zitadel...", file_path=str(file_path))
    while (time.time() - start_time) * 1000 < max_wait_ms:
        if file_path.exists():
            logger.info("File found!")
            return
        time.sleep(1)
    raise TimeoutError("Timeout waiting for file")


def _count_provisioned_resources(script_dir: Path) -> int:
    """Return 0 for now as Pulumi state management handles drift nicely."""
    return 0


def _destroy_existing(script_dir: Path, root_dir: Path) -> None:
    """
    Reset Zitadel to a completely clean state:
      1. Wipe Terraform state files — Terraform's record of what it built.
      2. Delete any leftover pat.json — it is a BIND MOUNT (not a Docker volume),
         so `docker compose down -v` does NOT remove it. A stale pat.json contains
         a PAT tied to the now-wiped database; using it would cause AUTH-7fs1e.
      3. Stop containers and delete volumes — destroys the Postgres database.

    We do NOT need `terraform destroy`. Deleting the database volume already removes
    every Zitadel resource at the storage level. The state file and pat.json are the
    only host-filesystem artefacts that must be cleared explicitly.
    """
    logger.info("🔥 Resetting existing Zitadel state...")

    # Step 1: Wipe the local Pulumi state for the Zitadel infrastructure.
    # Since we are destroying the database, Pulumi's state will be completely out of sync.
    pulumi_dir = script_dir.parent.parent / "cloud" / "zitadel"
    env = os.environ.copy()
    env["PULUMI_CONFIG_PASSPHRASE"] = "local"  # noqa: S105 - Ephemeral state passphrase for local dev environment bootstrap
    subprocess.run(  # noqa: S603
        [PULUMI_BIN, "stack", "rm", "local", "--yes", "--force"],
        cwd=pulumi_dir,
        env=env,
        check=False,
    )
    # Step 2: Delete stale pat.json from the bind-mount directory.
    # docker compose down -v does NOT delete bind-mounted host directories.
    pat_key_path = script_dir.parent.parent / "cloud" / "zitadel" / "machinekey" / "pat.json"
    if pat_key_path.exists():
        pat_key_path.unlink()
        logger.info("  Cleared: machinekey/pat.json (stale token for wiped database)")

    # Step 3: Stop ALL containers and wipe all named volumes (destroys Postgres databases)
    # This ensures that when Zitadel is reset, all downstream apps are also wiped,
    # preventing stale ID references (e.g., idp_user_id conflicts).
    subprocess.run(  # noqa: S603 - Docker compose is a trusted local executable
        [
            DOCKER_BIN,
            "compose",
            "--env-file",
            ".env",
            "--env-file",
            "versions.env",
            "-f",
            "docker-compose.yml",
            "-f",
            "docker-compose.identity.yml",
            "down",
            "-v",
            "--remove-orphans",
        ],
        cwd=root_dir,
        check=True,
    )

    logger.info("✅ Full infrastructure state cleared. Ready for fresh bootstrap.")


def _sync_outputs_to_env(root_dir: Path, env: dict[str, str]) -> None:
    """
    Sync Terraform outputs to .env by calling sync.py directly
    (avoids a cross-runtime dependency on pnpm/Node.js).
    """
    sync_script = root_dir / "infra" / "local" / "zitadel" / "sync.py"
    subprocess.run([sys.executable, str(sync_script)], cwd=root_dir, env=env, check=True)  # noqa: S603 - sys.executable is a trusted path


def _run_full_bootstrap(script_dir: Path, root_dir: Path, pat_key_path: Path) -> None:
    """
    Full bootstrap flow:
      1. Start Zitadel (fresh database generates a new ephemeral PAT)
      2. Wait for the ephemeral PAT
      3. Provision Zitadel resources with Pulumi
      4. Sync Pulumi outputs to .env
      5. Delete the ephemeral PAT
    """
    # Start Zitadel so it generates a fresh PAT on the clean database
    subprocess.run(  # noqa: S603 - Docker compose is a trusted local executable
        [
            DOCKER_BIN,
            "compose",
            "--env-file",
            ".env",
            "--env-file",
            "versions.env",
            "-f",
            "docker-compose.identity.yml",
            "up",
            "-d",
        ],
        cwd=root_dir,
        check=True,
    )

    # Wait for Zitadel's FirstInstance job to write the ephemeral PAT
    wait_for_file(pat_key_path)

    # Read the raw PAT (plain token or JSON-wrapped)
    raw_key = pat_key_path.read_text(encoding="utf-8").strip()
    actual_token = raw_key
    if raw_key.startswith("{"):
        try:
            key_data = json.loads(raw_key)
            actual_token = key_data.get("token") or key_data.get("Token") or raw_key
        except json.JSONDecodeError:
            pass  # raw_key is already the plain token string

    logger.info("Successfully read PAT from pat.json")

    # Wait for Zitadel's API to fully start up and CQRS projections to settle
    logger.info("Waiting 15 seconds for Zitadel projections to settle...")
    time.sleep(15)

    # The pulumiverse-zitadel v0.2.0 provider has a bug where it cannot authenticate via PATs.
    # We must generate a Machine Key (JWT Profile) for a temporary provisioner user.
    domain = "ucp.localhost:8080"
    headers = {
        "Authorization": f"Bearer {actual_token}",
        "Content-Type": "application/json",
        "Accept": "application/json",
    }

    def post(path, data):
        url = f"http://{domain}{path}"
        req = urllib.request.Request(  # noqa: S310 - internal API call to local zitadel instance
            url, data=json.dumps(data).encode("utf-8"), headers=headers, method="POST"
        )
        try:
            resp = urllib.request.urlopen(req)  # noqa: S310 - internal API call to local zitadel instance
            return json.loads(resp.read())
        except urllib.error.HTTPError as e:
            logger.exception(
                "zitadel_http_api_error",
                status_code=e.code,
                response_body=e.read().decode("utf-8", errors="replace"),
            )
            raise

    logger.info("Generating Machine Key for Pulumi provider...")
    provisioner_name = f"pulumi-provisioner-{uuid.uuid4().hex[:8]}"
    user_resp = post(
        "/management/v1/users/machine",
        {"userName": provisioner_name, "name": "Pulumi Bootstrap Provisioner"},
    )
    user_id = user_resp["userId"]

    logger.info("Granting IAM_OWNER role to Pulumi provisioner...")
    post("/admin/v1/members", {"userId": user_id, "roles": ["IAM_OWNER"]})

    key_resp = post(
        f"/management/v1/users/{user_id}/keys",
        {"type": "KEY_TYPE_JSON", "expirationDate": "2030-01-01T00:00:00Z"},
    )

    jwt_profile_json = base64.b64decode(key_resp["keyDetails"]).decode("utf-8")
    jwt_profile_path = pat_key_path.parent / "jwt_profile.json"
    jwt_profile_path.write_text(jwt_profile_json)

    try:
        # Provision Zitadel IAM resources via Pulumi
        logger.info("Applying Pulumi configuration...")
        env = os.environ.copy()
        env["PULUMI_CONFIG_PASSPHRASE"] = "local"  # noqa: S105 - Ephemeral state passphrase for local dev environment bootstrap  # noqa: S105 - local development passphrase is intentionally hardcoded
        env["IDENTITY_JWT_PROFILE_FILE"] = str(jwt_profile_path)
        env["IDENTITY_DOMAIN"] = "ucp.localhost"
        env["IDENTITY_INSECURE"] = "true"
        env["IDENTITY_PORT"] = "8080"

        # Remove any lingering IDENTITY_TOKEN from env that might confuse the provider
        if "IDENTITY_TOKEN" in env:
            del env["IDENTITY_TOKEN"]

        pulumi_dir = script_dir.parent.parent / "cloud" / "zitadel"

        # Ensure the 'local' stack exists and is selected before deploying
        subprocess.run(  # noqa: S603 - Pulumi is a trusted local executable
            [PULUMI_BIN, "stack", "select", "local", "--create"],
            cwd=pulumi_dir,
            env=env,
            check=True,
        )

        subprocess.run(  # noqa: S603 - Pulumi is a trusted local executable
            [PULUMI_BIN, "config", "set", "insecure", "true"],
            cwd=pulumi_dir,
            env=env,
            check=True,
        )
        subprocess.run(  # noqa: S603 - Pulumi is a trusted local executable
            [PULUMI_BIN, "config", "set", "port", "8080"],
            cwd=pulumi_dir,
            env=env,
            check=True,
        )

        # Use a consistent known password for local development instead of auto-generating
        secure_password = "FlowwolfLocal123!"  # noqa: S105 - Local development bootstrap password
        subprocess.run(  # noqa: S603 - Pulumi is a trusted local executable
            [PULUMI_BIN, "config", "set", "--secret", "platform_admin_password", secure_password],
            cwd=pulumi_dir,
            env=env,
            check=True,
        )

        subprocess.run(  # noqa: S603 - Pulumi is a trusted local executable
            [PULUMI_BIN, "up", "--yes", "--skip-preview"],
            cwd=pulumi_dir,
            env=env,
            check=True,
        )

        # Sync the new outputs to .env
        _sync_outputs_to_env(root_dir, env)

        logger.info("✅ Zitadel bootstrap completed successfully!")
    finally:
        # Cleanup the ephemeral PAT and generated jwt_profile — they must not linger on disk
        logger.info("Cleaning up local ephemeral credentials...")
        pat_key_path.unlink(missing_ok=True)
        jwt_profile_path = pat_key_path.parent / "jwt_profile.json"
        jwt_profile_path.unlink(missing_ok=True)


def main() -> None:
    script_dir = Path(__file__).parent.resolve()
    root_dir = script_dir.parent.parent.parent
    pat_key_path = script_dir.parent.parent / "cloud" / "zitadel" / "machinekey" / "pat.json"
    # Always wipe the old state and database volumes on bootstrap
    # to guarantee a completely fresh environment and token generation.
    _destroy_existing(script_dir, root_dir)

    _run_full_bootstrap(script_dir, root_dir, pat_key_path)


if __name__ == "__main__":
    try:
        main()
    except TimeoutError:
        logger.exception("\n❌ Bootstrap timed out")
        sys.exit(1)
    except RuntimeError:
        logger.exception("\n❌ Bootstrap configuration error")
        sys.exit(1)
    except subprocess.CalledProcessError:
        sys.exit(1)
    except KeyboardInterrupt:
        logger.exception("\nBootstrap cancelled by user.")
        sys.exit(0)
