"""global_initial_schema

Revision ID: 142d93fd6c4c
Revises:
Create Date: 2026-07-06 14:56:17.633049

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "142d93fd6c4c"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "database_shards",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("dsn", sa.String(length=1024), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "system_audit_log",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("trace_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("event", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_system_audit_log_tenant_time",
        "system_audit_log",
        ["tenant_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_audit_log_trace_id"), "system_audit_log", ["trace_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("idp_user_id", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idp_user_id"),
    )
    op.create_index(
        "uq_users_email_lower", "users", [sa.literal_column("lower(email)")], unique=True
    )
    op.create_table(
        "tenants",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("idp_tenant_id", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("shard_id", sa.Integer(), nullable=False),
        sa.Column("tier", sa.String(length=50), nullable=False),
        sa.Column("allow_private_as2", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("shard_schema", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["shard_id"],
            ["database_shards.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idp_tenant_id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("shard_schema"),
    )
    op.create_table(
        "as2_partners",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("is_local", sa.Boolean(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("as2_id", sa.String(length=255), nullable=False),
        sa.Column("public_cert_pem", sa.Text(), nullable=True),
        sa.Column("public_cert_vault_ref", sa.String(length=255), nullable=True),
        sa.Column("private_key_vault_ref", sa.String(length=255), nullable=True),
        sa.Column("prev_public_cert_pem", sa.Text(), nullable=True),
        sa.Column("prev_public_cert_vault_ref", sa.String(length=255), nullable=True),
        sa.Column("prev_private_key_vault_ref", sa.String(length=255), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "as2_id", name="uq_tenant_as2_id"),
    )
    op.create_index(
        "uq_global_as2_id",
        "as2_partners",
        ["as2_id"],
        unique=True,
        postgresql_where=sa.text("tenant_id IS NULL"),
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("idempotency_key", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        "ix_global_outbox_pending",
        "outbox",
        ["status", "created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.create_table(
        "sftp_partners",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("host", sa.String(length=1024), nullable=False),
        sa.Column("port", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=False),
        sa.Column("host_key", sa.Text(), nullable=True),
        sa.Column("inbound_remote_path", sa.String(length=1024), nullable=True),
        sa.Column("outbound_remote_path", sa.String(length=1024), nullable=True),
        sa.Column("password_encrypted", sa.String(length=1024), nullable=True),
        sa.Column("credentials_vault_ref", sa.String(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sftp_partners_tenant_id"), "sftp_partners", ["tenant_id"], unique=False
    )
    op.create_table(
        "tenant_users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("role", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "user_id", name="uq_tenant_user"),
    )
    op.create_table(
        "webhooks",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("auth_header_vault_ref", sa.String(length=255), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_webhooks_tenant_id"), "webhooks", ["tenant_id"], unique=False)
    op.create_table(
        "as2_partnerships",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("local_partner_id", sa.UUID(), nullable=False),
        sa.Column("remote_partner_id", sa.UUID(), nullable=False),
        sa.Column("credentials_vault_ref", sa.String(length=255), nullable=True),
        sa.Column("mdn_type", sa.String(length=50), nullable=False),
        sa.Column("mdn_url", sa.String(length=1024), nullable=True),
        sa.Column("encryption_algorithm", sa.String(length=50), nullable=False),
        sa.Column("signature_algorithm", sa.String(length=50), nullable=False),
        sa.Column("advanced_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["local_partner_id"], ["as2_partners.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["remote_partner_id"], ["as2_partners.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("local_partner_id", "remote_partner_id", name="uq_as2_partnership"),
    )
    op.create_table(
        "inbound_routes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("isa_sender_id", sa.String(length=255), nullable=False),
        sa.Column("isa_receiver_id", sa.String(length=255), nullable=False),
        sa.Column("transaction_type", sa.String(length=50), nullable=False),
        sa.Column(
            "processing_mode", sa.String(length=50), server_default="TRANSLATE", nullable=False
        ),
        sa.Column("webhook_id", sa.UUID(), nullable=True),
        sa.Column("as2_partner_id", sa.UUID(), nullable=True),
        sa.Column("sftp_partner_id", sa.UUID(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "(webhook_id IS NOT NULL)::int + (as2_partner_id IS NOT NULL)::int + (sftp_partner_id IS NOT NULL)::int = 1",
            name="chk_inbound_routes_exactly_one_dest",
        ),
        sa.ForeignKeyConstraint(
            ["as2_partner_id"],
            ["as2_partners.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sftp_partner_id"],
            ["sftp_partners.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["webhook_id"],
            ["webhooks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inbound_routes_tenant_id"), "inbound_routes", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_inbound_routes_unique_active",
        "inbound_routes",
        ["tenant_id", "isa_sender_id", "isa_receiver_id", "transaction_type"],
        unique=True,
        postgresql_where=sa.text("active = true"),
    )
    op.create_table(
        "outbound_routes",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("tenant_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("isa_sender_id", sa.String(length=255), nullable=False),
        sa.Column("isa_receiver_id", sa.String(length=255), nullable=False),
        sa.Column("transaction_type", sa.String(length=50), nullable=False),
        sa.Column(
            "processing_mode", sa.String(length=50), server_default="TRANSLATE", nullable=False
        ),
        sa.Column("as2_partner_id", sa.UUID(), nullable=True),
        sa.Column("sftp_partner_id", sa.UUID(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "(as2_partner_id IS NOT NULL)::int + (sftp_partner_id IS NOT NULL)::int = 1",
            name="chk_outbound_routes_exactly_one_dest",
        ),
        sa.ForeignKeyConstraint(
            ["as2_partner_id"],
            ["as2_partners.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sftp_partner_id"],
            ["sftp_partners.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_outbound_routes_tenant_id"), "outbound_routes", ["tenant_id"], unique=False
    )
    op.create_index(
        "ix_outbound_routes_unique_active",
        "outbound_routes",
        ["tenant_id", "isa_sender_id", "isa_receiver_id", "transaction_type"],
        unique=True,
        postgresql_where=sa.text("active = true"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_outbound_routes_unique_active",
        table_name="outbound_routes",
        postgresql_where=sa.text("active = true"),
    )
    op.drop_index(op.f("ix_outbound_routes_tenant_id"), table_name="outbound_routes")
    op.drop_table("outbound_routes")
    op.drop_index(
        "ix_inbound_routes_unique_active",
        table_name="inbound_routes",
        postgresql_where=sa.text("active = true"),
    )
    op.drop_index(op.f("ix_inbound_routes_tenant_id"), table_name="inbound_routes")
    op.drop_table("inbound_routes")
    op.drop_table("as2_partnerships")
    op.drop_index(op.f("ix_webhooks_tenant_id"), table_name="webhooks")
    op.drop_table("webhooks")
    op.drop_table("tenant_users")
    op.drop_index(op.f("ix_sftp_partners_tenant_id"), table_name="sftp_partners")
    op.drop_table("sftp_partners")
    op.drop_index(
        "ix_global_outbox_pending",
        table_name="outbox",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_table("outbox")
    op.drop_index(
        "uq_global_as2_id", table_name="as2_partners", postgresql_where=sa.text("tenant_id IS NULL")
    )
    op.drop_table("as2_partners")
    op.drop_table("tenants")
    op.drop_index("uq_users_email_lower", table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_system_audit_log_trace_id"), table_name="system_audit_log")
    op.drop_index("ix_system_audit_log_tenant_time", table_name="system_audit_log")
    op.drop_table("system_audit_log")
    op.drop_table("database_shards")
    # ### end Alembic commands ###
