from typing import Protocol


class ReplicationPort(Protocol):
    async def replicate_tenant_configuration(self, tenant_id: str) -> None:
        """Full tenant state sync. Retained only for global broadcasts (PROVISION_ALL_TENANTS)."""
        ...

    async def replicate_as2_partner(self, tenant_id: str, partner_id: str) -> None: ...
    async def delete_as2_partner(self, tenant_id: str, partner_id: str) -> None: ...

    async def replicate_as2_partnership(self, tenant_id: str, partnership_id: str) -> None: ...
    async def delete_as2_partnership(self, tenant_id: str, partnership_id: str) -> None: ...

    async def replicate_sftp_partner(self, tenant_id: str, partner_id: str) -> None: ...
    async def delete_sftp_partner(self, tenant_id: str, partner_id: str) -> None: ...

    async def replicate_webhook(self, tenant_id: str, webhook_id: str) -> None: ...
    async def delete_webhook(self, tenant_id: str, webhook_id: str) -> None: ...

    async def replicate_inbound_route(self, tenant_id: str, route_id: str) -> None: ...
    async def delete_inbound_route(self, tenant_id: str, route_id: str) -> None: ...

    async def replicate_outbound_route(self, tenant_id: str, route_id: str) -> None: ...
    async def delete_outbound_route(self, tenant_id: str, route_id: str) -> None: ...

    async def replicate_outbound_edi_header(self, tenant_id: str, header_id: str) -> None: ...
    async def delete_outbound_edi_header(self, tenant_id: str, header_id: str) -> None: ...
