from enum import StrEnum


class PipelineEventType(StrEnum):
    TRANSFORM_EVENT = "TRANSFORM_EVENT"
    COMPUTE_TRANSFORM_EVENT = "COMPUTE_TRANSFORM_EVENT"
    TRANSFORM_COMPLETED = "TRANSFORM_COMPLETED"
    DELIVER_EVENT = "DELIVER_EVENT"
    DELIVERY_COMPLETED = "DELIVERY_COMPLETED"


class ProvisioningEventType(StrEnum):
    AS2_PARTNER_CREATED = "AS2_PARTNER_CREATED"
    AS2_PARTNER_UPDATED = "AS2_PARTNER_UPDATED"
    AS2_PARTNER_DELETED = "AS2_PARTNER_DELETED"
    AS2_PARTNERSHIP_CREATED = "AS2_PARTNERSHIP_CREATED"
    AS2_PARTNERSHIP_UPDATED = "AS2_PARTNERSHIP_UPDATED"
    AS2_PARTNERSHIP_DELETED = "AS2_PARTNERSHIP_DELETED"
    SFTP_PARTNER_CREATED = "SFTP_PARTNER_CREATED"
    SFTP_PARTNER_UPDATED = "SFTP_PARTNER_UPDATED"
    SFTP_PARTNER_DELETED = "SFTP_PARTNER_DELETED"
    WEBHOOK_CREATED = "WEBHOOK_CREATED"
    WEBHOOK_UPDATED = "WEBHOOK_UPDATED"
    WEBHOOK_DELETED = "WEBHOOK_DELETED"
    INBOUND_ROUTE_CREATED = "INBOUND_ROUTE_CREATED"
    INBOUND_ROUTE_UPDATED = "INBOUND_ROUTE_UPDATED"
    INBOUND_ROUTE_DELETED = "INBOUND_ROUTE_DELETED"
    OUTBOUND_ROUTE_CREATED = "OUTBOUND_ROUTE_CREATED"
    OUTBOUND_ROUTE_UPDATED = "OUTBOUND_ROUTE_UPDATED"
    OUTBOUND_ROUTE_DELETED = "OUTBOUND_ROUTE_DELETED"
    OUTBOUND_EDI_HEADER_CREATED = "OUTBOUND_EDI_HEADER_CREATED"
    OUTBOUND_EDI_HEADER_UPDATED = "OUTBOUND_EDI_HEADER_UPDATED"
    OUTBOUND_EDI_HEADER_DELETED = "OUTBOUND_EDI_HEADER_DELETED"


class MessageQueueName(StrEnum):
    TRANSFORM_ORCHESTRATION_QUEUE = "TransformOrchestrationQueue"
    DELIVER_QUEUE = "DeliverQueue"
    PROVISIONING_QUEUE = "ProvisioningQueue"
    TRANSFORM_COMPUTE_QUEUE = "TransformComputeQueue"
    CDC_DLQ_QUEUE = "CDC-DLQ"
