from enum import StrEnum


class ProvisioningEventType(StrEnum):
    AS2_PARTNER_CREATED = "AS2_PARTNER_CREATED"
    AS2_PARTNER_UPDATED = "AS2_PARTNER_UPDATED"
    AS2_PARTNER_DELETED = "AS2_PARTNER_DELETED"
    AS2_PARTNERSHIP_CREATED = "AS2_PARTNERSHIP_CREATED"
    AS2_PARTNERSHIP_UPDATED = "AS2_PARTNERSHIP_UPDATED"
    AS2_PARTNERSHIP_DELETED = "AS2_PARTNERSHIP_DELETED"
    SFTP_PARTNER_CREATED = "SFTP_PARTNER_CREATED"
    SFTP_PARTNER_UPDATED = "SFTP_PARTNER_UPDATED"
    SFTP_PARTNER_DELETED = "SFTP_PARTNER_DELETED"
    WEBHOOK_CREATED = "WEBHOOK_CREATED"
    WEBHOOK_UPDATED = "WEBHOOK_UPDATED"
    WEBHOOK_DELETED = "WEBHOOK_DELETED"
    INBOUND_ROUTE_CREATED = "INBOUND_ROUTE_CREATED"
    INBOUND_ROUTE_UPDATED = "INBOUND_ROUTE_UPDATED"
    INBOUND_ROUTE_DELETED = "INBOUND_ROUTE_DELETED"
    OUTBOUND_ROUTE_CREATED = "OUTBOUND_ROUTE_CREATED"
    OUTBOUND_ROUTE_UPDATED = "OUTBOUND_ROUTE_UPDATED"
    OUTBOUND_ROUTE_DELETED = "OUTBOUND_ROUTE_DELETED"


class MessageQueueName(StrEnum):
    TRANSLATE = "TranslateQueue"
    DELIVER = "DeliverQueue"
    PROVISIONING = "ProvisioningQueue"
