"""tenant_initial_schema

Revision ID: 1cff61426f2b
Revises:
Create Date: 2026-06-29 18:20:42.581371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1cff61426f2b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ack_receipts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ack_receipts_tenant_id'), 'ack_receipts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_ack_receipts_trace_id'), 'ack_receipts', ['trace_id'], unique=False)
    op.create_table('api_payloads',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('inbound_route_id', sa.UUID(), nullable=True),
    sa.Column('outbound_route_id', sa.UUID(), nullable=True),
    sa.Column('webhook_url', sa.String(length=1024), nullable=True),
    sa.Column('http_status_code', sa.Integer(), nullable=True),
    sa.Column('target_format', sa.String(length=50), nullable=True),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_payloads_tenant_id'), 'api_payloads', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_api_payloads_trace_id'), 'api_payloads', ['trace_id'], unique=False)
    op.create_table('as2_partners',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('is_local', sa.Boolean(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('as2_id', sa.String(length=255), nullable=False),
    sa.Column('public_cert_pem', sa.Text(), nullable=True),
    sa.Column('public_cert_vault_ref', sa.String(length=255), nullable=True),
    sa.Column('private_key_vault_ref', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('step', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_audit_log_trace_id'), 'audit_log', ['trace_id'], unique=False)
    op.create_table('edi_messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('connection_type', sa.String(length=50), nullable=False),
    sa.Column('sender_id', sa.String(length=255), nullable=True),
    sa.Column('receiver_id', sa.String(length=255), nullable=True),
    sa.Column('as2_message_id', sa.String(length=255), nullable=True),
    sa.Column('interchange_control_no', sa.String(length=255), nullable=True),
    sa.Column('transaction_type', sa.String(length=50), nullable=True),
    sa.Column('format_standard', sa.String(length=50), nullable=True),
    sa.Column('s3_key', sa.String(length=1024), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edi_messages_tenant_id'), 'edi_messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_edi_messages_trace_id'), 'edi_messages', ['trace_id'], unique=False)
    op.create_index('ix_edi_msgs_sender_recv', 'edi_messages', ['sender_id', 'receiver_id', 'created_at'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('trace_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_jobs_trace_id'), 'jobs', ['trace_id'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_outbox_tenant_id'), 'outbox', ['tenant_id'], unique=False)
    op.create_index('ix_tenant_outbox_pending', 'outbox', ['status', 'created_at'], unique=False, postgresql_where=sa.text("status = 'PENDING'"))
    op.create_table('processed_events',
    sa.Column('idempotency_key', sa.UUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_processed_events_tenant_id'), 'processed_events', ['tenant_id'], unique=False)
    op.create_table('sftp_partners',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('host', sa.String(length=1024), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('remote_path', sa.String(length=1024), nullable=True),
    sa.Column('credentials_vault_ref', sa.String(length=255), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sftp_partners_tenant_id'), 'sftp_partners', ['tenant_id'], unique=False)
    op.create_table('webhook_partners',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('auth_header_vault_ref', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_webhook_partners_tenant_id'), 'webhook_partners', ['tenant_id'], unique=False)
    op.create_table('as2_partnerships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('local_partner_id', sa.UUID(), nullable=False),
    sa.Column('remote_partner_id', sa.UUID(), nullable=False),
    sa.Column('host', sa.String(length=1024), nullable=True),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('credentials_vault_ref', sa.String(length=255), nullable=True),
    sa.Column('mdn_type', sa.String(length=50), nullable=False),
    sa.Column('mdn_url', sa.String(length=1024), nullable=True),
    sa.Column('encryption_algorithm', sa.String(length=50), nullable=False),
    sa.Column('signature_algorithm', sa.String(length=50), nullable=False),
    sa.Column('advanced_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['local_partner_id'], ['as2_partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['remote_partner_id'], ['as2_partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inbound_routes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('isa_sender_id', sa.String(length=255), nullable=False),
    sa.Column('isa_receiver_id', sa.String(length=255), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('webhook_partner_id', sa.UUID(), nullable=True),
    sa.Column('as2_partner_id', sa.UUID(), nullable=True),
    sa.Column('sftp_partner_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['as2_partner_id'], ['as2_partners.id'], ),
    sa.ForeignKeyConstraint(['sftp_partner_id'], ['sftp_partners.id'], ),
    sa.ForeignKeyConstraint(['webhook_partner_id'], ['webhook_partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint(
        '(webhook_partner_id IS NOT NULL)::integer + '
        '(as2_partner_id IS NOT NULL)::integer + '
        '(sftp_partner_id IS NOT NULL)::integer = 1',
        name='chk_inbound_routes_exactly_one_dest'
    )
    )
    op.create_index(op.f('ix_inbound_routes_tenant_id'), 'inbound_routes', ['tenant_id'], unique=False)
    op.create_index(
        'ix_inbound_routes_unique_active',
        'inbound_routes',
        ['tenant_id', 'isa_sender_id', 'isa_receiver_id', 'transaction_type'],
        unique=True,
        postgresql_where=sa.text("active = true")
    )
    op.create_table('outbound_routes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('isa_sender_id', sa.String(length=255), nullable=False),
    sa.Column('isa_receiver_id', sa.String(length=255), nullable=False),
    sa.Column('transaction_type', sa.String(length=50), nullable=False),
    sa.Column('as2_partner_id', sa.UUID(), nullable=True),
    sa.Column('sftp_partner_id', sa.UUID(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['as2_partner_id'], ['as2_partners.id'], ),
    sa.ForeignKeyConstraint(['sftp_partner_id'], ['sftp_partners.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.CheckConstraint(
        '(as2_partner_id IS NOT NULL)::integer + '
        '(sftp_partner_id IS NOT NULL)::integer = 1',
        name='chk_outbound_routes_exactly_one_dest'
    )
    )
    op.create_index(op.f('ix_outbound_routes_tenant_id'), 'outbound_routes', ['tenant_id'], unique=False)
    op.create_index(
        'ix_outbound_routes_unique_active',
        'outbound_routes',
        ['tenant_id', 'isa_sender_id', 'isa_receiver_id', 'transaction_type'],
        unique=True,
        postgresql_where=sa.text("active = true")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbound_routes_tenant_id'), table_name='outbound_routes')
    op.drop_table('outbound_routes')
    op.drop_index(op.f('ix_inbound_routes_tenant_id'), table_name='inbound_routes')
    op.drop_table('inbound_routes')
    op.drop_table('as2_partnerships')
    op.drop_index(op.f('ix_webhook_partners_tenant_id'), table_name='webhook_partners')
    op.drop_table('webhook_partners')
    op.drop_index(op.f('ix_sftp_partners_tenant_id'), table_name='sftp_partners')
    op.drop_table('sftp_partners')
    op.drop_index(op.f('ix_processed_events_tenant_id'), table_name='processed_events')
    op.drop_table('processed_events')
    op.drop_index('ix_tenant_outbox_pending', table_name='outbox', postgresql_where=sa.text("status = 'PENDING'"))
    op.drop_index(op.f('ix_outbox_tenant_id'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_jobs_trace_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_edi_msgs_sender_recv', table_name='edi_messages')
    op.drop_index(op.f('ix_edi_messages_trace_id'), table_name='edi_messages')
    op.drop_index(op.f('ix_edi_messages_tenant_id'), table_name='edi_messages')
    op.drop_table('edi_messages')
    op.drop_index(op.f('ix_audit_log_trace_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('as2_partners')
    op.drop_index(op.f('ix_api_payloads_trace_id'), table_name='api_payloads')
    op.drop_index(op.f('ix_api_payloads_tenant_id'), table_name='api_payloads')
    op.drop_table('api_payloads')
    op.drop_index(op.f('ix_ack_receipts_trace_id'), table_name='ack_receipts')
    op.drop_index(op.f('ix_ack_receipts_tenant_id'), table_name='ack_receipts')
    op.drop_table('ack_receipts')
    # ### end Alembic commands ###
