"""tenant_initial_schema

Revision ID: 534f8e33d17d
Revises:
Create Date: 2026-06-25 09:43:48.632423

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '534f8e33d17d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('as2_payloads',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('as2_from', sa.String(length=255), nullable=False),
    sa.Column('as2_to', sa.String(length=255), nullable=False),
    sa.Column('raw_headers', sa.Text(), nullable=True),
    sa.Column('payload_storage_uri', sa.String(length=2048), nullable=True),
    sa.Column('mic', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_as2_payloads_message_id'), 'as2_payloads', ['message_id'], unique=False)
    op.create_index(op.f('ix_as2_payloads_tenant_id'), 'as2_payloads', ['tenant_id'], unique=False)
    op.create_table('trading_partners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('as2_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('public_cert_pem', sa.Text(), nullable=True),
    sa.Column('is_host_identity', sa.Boolean(), nullable=False),
    sa.Column('private_key_pem', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'as2_id', name='uq_tenant_as2_id')
    )
    op.create_index(op.f('ix_trading_partners_tenant_id'), 'trading_partners', ['tenant_id'], unique=False)

    # Enable Row-Level Security
    op.execute("ALTER TABLE as2_payloads ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY tenant_isolation_policy ON as2_payloads USING (tenant_id = current_setting('app.current_tenant')::integer);")

    op.execute("ALTER TABLE trading_partners ENABLE ROW LEVEL SECURITY;")
    op.execute("CREATE POLICY tenant_isolation_policy ON trading_partners USING (tenant_id = current_setting('app.current_tenant')::integer);")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON trading_partners;")
    op.execute("ALTER TABLE trading_partners DISABLE ROW LEVEL SECURITY;")
    op.execute("DROP POLICY IF EXISTS tenant_isolation_policy ON as2_payloads;")
    op.execute("ALTER TABLE as2_payloads DISABLE ROW LEVEL SECURITY;")

    op.drop_index(op.f('ix_trading_partners_tenant_id'), table_name='trading_partners')
    op.drop_table('trading_partners')
    op.drop_index(op.f('ix_as2_payloads_tenant_id'), table_name='as2_payloads')
    op.drop_index(op.f('ix_as2_payloads_message_id'), table_name='as2_payloads')
    op.drop_table('as2_payloads')
    # ### end Alembic commands ###
