"""Add partial unique index for active host identity

Revision ID: e5d979a9ffbd
Revises: 534f8e33d17d
Create Date: 2026-06-25 22:18:13.593145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5d979a9ffbd'
down_revision: Union[str, Sequence[str], None] = '534f8e33d17d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_partners', sa.Column('private_key_ciphertext', sa.Text(), nullable=True))
    op.add_column('trading_partners', sa.Column('kms_key_id', sa.String(length=255), nullable=True))
    op.add_column('trading_partners', sa.Column('private_key_secret_id', sa.String(length=255), nullable=True))
    op.add_column('trading_partners', sa.Column('key_version', sa.Integer(), nullable=False))
    op.create_index('ix_tenant_active_host_identity', 'trading_partners', ['tenant_id'], unique=True, postgresql_where=sa.text('is_host_identity IS true AND is_active IS true'))
    op.drop_column('trading_partners', 'private_key_pem')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trading_partners', sa.Column('private_key_pem', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('ix_tenant_active_host_identity', table_name='trading_partners', postgresql_where=sa.text('is_host_identity IS true AND is_active IS true'))
    op.drop_column('trading_partners', 'key_version')
    op.drop_column('trading_partners', 'private_key_secret_id')
    op.drop_column('trading_partners', 'kms_key_id')
    op.drop_column('trading_partners', 'private_key_ciphertext')
    # ### end Alembic commands ###
