[project]
name = "identity-worker"
version = "0.1.0"
description = "Identity Background Worker"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "platform-orm",
    "identity",
    "observability",
    "ucp",
    "ucp_models",
    "aioboto3>=13.1.1",
    "sqlalchemy>=2.0.29",
    "asyncpg>=0.29.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
platform-orm = { workspace = true }
identity = { workspace = true }
observability = { workspace = true }
ucp = { workspace = true }
ucp_models = { workspace = true }
