import asyncio

# Alembic strictly requires standard logging to parse its config file.
# Ignored TID251 inline because Ruff per-file-ignores fails to match in this monorepo context.
from logging.config import fileConfig  # noqa: TID251

from alembic import context
from alembic.autogenerate.api import AutogenContext
from database.testing import get_test_shard_url_sync
from database.utils import normalize_to_asyncpg, shard_connect_args
from sqlalchemy import pool
from sqlalchemy.engine import Connection
from sqlalchemy.ext.asyncio import create_async_engine

from edi.adapters.outbound.database.models.data_plane import SanitizedText, TenantBase
from edi.config.settings import get_settings

config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name, disable_existing_loggers=False)

target_metadata = TenantBase.metadata

# For generating migrations, we connect to shard 1 as a representative database
_ini_url = config.get_main_option("sqlalchemy.url")
if _ini_url:
    TENANT_DB_URL = _ini_url
else:
    global_url = str(get_settings().database.global_url)
    TENANT_DB_URL = get_test_shard_url_sync(global_url)


from typing import Any, Literal


def render_item(type_: str, obj: Any, autogen_context: AutogenContext) -> str | Literal[False]:
    """Render SanitizedText as Text() in autogenerated migrations.

    SanitizedText is a Python-only TypeDecorator (no DDL difference from Text).
    Without this hook, Alembic emits the full module path which breaks migrations.
    """
    if type_ == "type" and isinstance(obj, SanitizedText):
        autogen_context.imports.add("from sqlalchemy import Text")
        return "Text()"
    return False


def run_migrations_offline() -> None:
    """Run migrations in 'offline' mode."""
    context.configure(
        url=TENANT_DB_URL,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
        include_schemas=True,
    )

    with context.begin_transaction():
        context.run_migrations()


def do_run_migrations(connection: Connection) -> None:
    context.configure(
        connection=connection,
        target_metadata=target_metadata,
        include_schemas=True,
        render_item=render_item,
    )

    with context.begin_transaction():
        context.run_migrations()


async def run_async_migrations() -> None:
    normalized_url = normalize_to_asyncpg(TENANT_DB_URL)

    # Explicitly enforce search_path=public via the centralized shard_connect_args()
    # utility so PostgreSQL never uses the implicit "$user" schema.
    connectable = create_async_engine(
        normalized_url or TENANT_DB_URL,
        poolclass=pool.NullPool,
        connect_args=shard_connect_args(),
    )

    async with connectable.connect() as connection:
        await connection.run_sync(do_run_migrations)

    await connectable.dispose()


def run_migrations_online() -> None:
    """Run migrations in 'online' mode."""
    asyncio.run(run_async_migrations())


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
