from enum import StrEnum


class AppEnvKeys(StrEnum):
    S3_BUCKET = "S3_BUCKET"
    AWS_SNS_TOPIC_ARN = "AWS_SNS_TOPIC_ARN"
    SQS_TRANSFORM_QUEUE_URL = "SQS_TRANSFORM_QUEUE_URL"
    SQS_DELIVER_QUEUE_URL = "SQS_DELIVER_QUEUE_URL"
    SQS_LIFECYCLE_QUEUE_URL = "SQS_LIFECYCLE_QUEUE_URL"
    SQS_DATA_PLANE_JOBS_QUEUE_URL = "SQS_DATA_PLANE_JOBS_QUEUE_URL"
    SQS_CONTROL_PLANE_JOBS_QUEUE_URL = "SQS_CONTROL_PLANE_JOBS_QUEUE_URL"
